src/OSPSuite.UI/Views/Importer/ImporterView.cs

Tests are not included here because the only change is in the UI code.

Fixes Open-Systems-Pharmacology/PK-Sim#78 - Crash when starting obs data import

---

src/OSPSuite.Infrastructure/OSPSuite.Infrastructure.csproj
src/OSPSuite.Infrastructure/packages.config
src/OSPSuite.Presentation/OSPSuite.Presentation.csproj
src/OSPSuite.Presentation/packages.config
tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj
tests/OSPSuite.Core.Tests/packages.config

Open-Systems-Pharmacology/MoBi#63

Cannot import due to incorrect version of SmartXLS

---

src/OSPSuite.Core/CoreRegister.cs
tests/OSPSuite.Core.Tests/Core/EventBuilderTaskIntegrationTests.cs
tests/OSPSuite.Core.Tests/Core/RegistrationSpecs.cs
tests/OSPSuite.Core.Tests/Helpers/UnitTestContextSpecificationSpecs.cs
tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj

and also Fixes Open-Systems-Pharmacology/PK-Sim/#96

Fixes Open-Systems-Pharmacology/PK-Sim/#94 Cannot run PI 

---

src/OSPSuite.Infrastructure/OSPSuite.Infrastructure.csproj
src/OSPSuite.Infrastructure/packages.config
src/OSPSuite.Presentation/OSPSuite.Presentation.csproj
src/OSPSuite.Presentation/packages.config
src/OSPSuite.UI/Views/Charts/ChartTemplateManagerView.cs
src/OSPSuite.UI/Views/Importer/ImporterView.Designer.cs
src/OSPSuite.UI/Views/Importer/ImporterView.cs
tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj
tests/OSPSuite.Core.Tests/packages.config

I have also updated SX to the latest version

Fixes #42 preview origin data button too small

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.UI/Controls/UxHtmlLabel.cs
src/OSPSuite.UI/Controls/UxRichEditControl.cs
src/OSPSuite.UI/OSPSuite.UI.csproj
src/OSPSuite.UI/Properties/licenses.licx
src/OSPSuite.UI/UIConstants.cs
src/OSPSuite.UI/Views/ExceptionView.Designer.cs
src/OSPSuite.UI/Views/ExceptionView.cs
tests/OSPSuite.Starter/Presenters/ImporterTestPresenter.cs

WIP Open-Systems-Pharmacology/InstallationValidator#88

WIP Open-Systems-Pharmacology/InstallationValidator#88

---

src/OSPSuite.UI/Controls/UxChartControl.cs

population plots are missing the context menu
Fixes Open-Systems-Pharmacology/PK-Sim#182

Fixes Open-Systems-Pharmacology/PK-Sim#182

---

src/OSPSuite.Core/Commands/RenameObservedDataCommand.cs
src/OSPSuite.Core/OSPSuite.Core.csproj
src/OSPSuite.Core/Services/CurveNamer.cs
src/OSPSuite.Core/Services/DataRepositoryNamer.cs
src/OSPSuite.Presentation/Presenters/Charts/ChartPresenter.cs
src/OSPSuite.Presentation/Services/Charts/ChartPresenterContext.cs
tests/OSPSuite.Core.Tests/Commands/RenameObservedDataCommandSpecs.cs
tests/OSPSuite.Core.Tests/Core/CurveNamerSpecs.cs
tests/OSPSuite.Core.Tests/Core/DataRepositoryNamerSpecs.cs
tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj
tests/OSPSuite.Core.Tests/Presentation/ParameterIdentificationPredictedVsObservedChartPresenterSpecs.cs
tests/OSPSuite.Core.Tests/Presentation/ParameterIdentificationResidualVsTimeChartPresenterSpecs.cs
tests/OSPSuite.Core.Tests/Presentation/ParameterIdentificationTimeProfileChartPresenterSpecs.cs

Some of this rename functionality can be shared if moved to core.

WIP - #108 curve name does not contain simulation name after cloning

---

src/OSPSuite.Core/IApplicationConfiguration.cs
src/OSPSuite.Infrastructure/Configuration/OSPSuiteConfiguration.cs
tests/OSPSuite.Starter/Tasks/ApplicationConfiguration.cs

Fixes #264 move application file management to core

---

src/OSPSuite.Core/Domain/ValueOrigin.cs
src/OSPSuite.Core/Serialization/Xml/ParameterOriginXmlSerializer.cs
src/OSPSuite.Core/Serialization/Xml/ValueOriginDeterminationMethodXmlAttributeMapper.cs
src/OSPSuite.Core/Serialization/Xml/ValueOriginSourceXmlAttributeMapper.cs
src/OSPSuite.Core/Serialization/Xml/ValueOriginXmlSerializer.cs
src/OSPSuite.UI/Binders/ValueOriginBinder.cs
tests/OSPSuite.Starter/Forms/GridViewForm.cs

ValueOrigin node will almost always be undefined undefined so I'd rather not save it to create over 8000! empty nodes in a pkml simulations
Same goes with Origin for parameter that I always wanted to change

Fixes #331 and Fixes #323

---

src/OSPSuite.Core/OSPSuite.Core.csproj
src/OSPSuite.Core/Reporting/ReportConfiguration.cs
src/OSPSuite.Core/Reporting/ReportTemplate.cs
src/OSPSuite.Core/packages.config
src/OSPSuite.Infrastructure/OSPSuite.Infrastructure.csproj
src/OSPSuite.Infrastructure/Reporting/ReportingRegister.cs
src/OSPSuite.Infrastructure/Reporting/ReportingTask.cs
src/OSPSuite.Presentation/OSPSuite.Presentation.csproj
src/OSPSuite.Presentation/Presenters/AbstractReportingPresenter.cs
src/OSPSuite.Presentation/Presenters/Main/AbstractMainViewPresenter.cs
src/OSPSuite.Presentation/Presenters/Main/IMainViewPresenter.cs
src/OSPSuite.Presentation/packages.config
src/OSPSuite.UI/OSPSuite.UI.csproj
src/OSPSuite.UI/Views/ReportingView.cs
src/OSPSuite.UI/packages.config
tests/OSPSuite.Starter/Presenters/ShellPresenter.cs

@Yuri05 This has been bugging me for a very long time. Using core would bring TexReporter
using infrastructure would bring presnetation=>devexpress etc.
This is now all cleaned up. Could be even better but good for now

518 infrastructure issue

---

src/OSPSuite.Core/Domain/Services/IDataRepositoryTask.cs
src/OSPSuite.Infrastructure/Services/DataRepositoryTask.cs
src/OSPSuite.Presentation/Services/ActiveSubjectRetriever.cs
tests/OSPSuite.Core.Tests/Core/DataRepositoryTaskSpecs.cs
tests/OSPSuite.Starter/OSPSuite.Starter.csproj
tests/OSPSuite.Starter/Presenters/DataRepositoryTestPresenter.cs
tests/OSPSuite.Starter/Views/DataRepositoryTestView.Designer.cs
tests/OSPSuite.Starter/Views/DataRepositoryTestView.cs

@Yuri05 The goal is to avoid that here
https://github.com/Open-Systems-Pharmacology/QualificationPlan/blob/master/examples/minimal/reporting%20engine%20input/ObservedData/Itraconazole%20600mg%20MD.csv
Where the SD Column is second
In the reporting Engine, there is no knowledge of AuxiliartyType, related columns ectc.. We have to work with conventions
Col 1: Time
Col 2: Observed Data
Col3: Error

564 export observed data

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Infrastructure.Export/OSPSuite.Infrastructure.Export.csproj
src/OSPSuite.Presentation.Importer/OSPSuite.Presentation.Importer.csproj
src/OSPSuite.R/Services/ContainerTask.cs
tests/OSPSuite.Core.IntegrationTests/OSPSuite.Core.IntegrationTests.csproj
tests/OSPSuite.R.Tests/Services/ContainerTaskSpecs.cs

Fixes #596 path as string

---

src/OSPSuite.Core/Domain/ObjectPath.cs
src/OSPSuite.Core/Domain/TimePath.cs
tests/OSPSuite.Core.Tests/Domain/ObjectPathSpecs.cs

@Yuri05 REquired for https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1320

Fixes allow update of path instance

---

src/OSPSuite.Assets.Images/OSPSuite.Assets.Images.csproj
src/OSPSuite.Assets/OSPSuite.Assets.csproj
src/OSPSuite.Core/OSPSuite.Core.csproj
src/OSPSuite.Infrastructure.Autofac/OSPSuite.Infrastructure.Autofac.csproj
src/OSPSuite.Infrastructure.Castle/OSPSuite.Infrastructure.Castle.csproj
src/OSPSuite.Infrastructure.Export/OSPSuite.Infrastructure.Export.csproj
src/OSPSuite.Infrastructure.Import/OSPSuite.Infrastructure.Import.csproj
src/OSPSuite.Infrastructure.Reporting/OSPSuite.Infrastructure.Reporting.csproj
src/OSPSuite.Infrastructure.Serialization/OSPSuite.Infrastructure.Serialization.csproj
src/OSPSuite.Infrastructure/OSPSuite.Infrastructure.csproj
src/OSPSuite.Presentation.Importer/OSPSuite.Presentation.Importer.csproj
src/OSPSuite.Presentation.Serialization/OSPSuite.Presentation.Serialization.csproj
src/OSPSuite.Presentation/OSPSuite.Presentation.csproj
src/OSPSuite.UI.Importer/OSPSuite.UI.Importer.csproj
src/OSPSuite.UI/OSPSuite.UI.csproj

Update debug flag to set pdb to full

---

src/OSPSuite.Infrastructure.Import/Core/DataFormat/AbstractColumnsDataFormat.cs
src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
tests/OSPSuite.Presentation.Tests/Importer/Core/DataFormat/DataFormat_MetaData_CSpecs.cs

Fix on issue https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/867

Columns are now selectable

---

src/OSPSuite.Infrastructure.Import/Core/DataFormat/AbstractColumnsDataFormat.cs
src/OSPSuite.Infrastructure.Import/Core/IDataFormat.cs
src/OSPSuite.Infrastructure.Import/Core/IDataSet.cs
src/OSPSuite.Infrastructure.Import/Core/Mappers/DataSetToDataRepositoryMapper.cs
src/OSPSuite.Infrastructure.Import/Extensions/ColumnInfoExtensions.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
tests/OSPSuite.Infrastructure.Tests/Import/DataSetToDataRepositoryMapperSpecs.cs
tests/OSPSuite.Infrastructure.Tests/Import/concern_for_DataSetToDataRepositoryMapperSpecs.cs
tests/OSPSuite.Presentation.Tests/Importer/Core/DataFormat/DataFormat_MetaData_CSpecs.cs
tests/OSPSuite.Presentation.Tests/Importer/Core/DataFormat/DataFormat_NonmemSpecs.cs

LLoq is used for threshold on the value

---

src/OSPSuite.Presentation/Presenters/Importer/ImportConfirmationPresenter.cs
src/OSPSuite.Presentation/Presenters/ObservedData/DataRepositoryChartPresenter.cs
src/OSPSuite.UI/Services/DataImporter.cs

926 log lin scale toggle fixed

---

appveyor.yml
src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs

Just a quick fix for a bug I found when plugging in to MoBi

Apply configuration fix

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs

#984 Invalid entries

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.UI/Views/Importer/ModalImporterView.Designer.cs

#985 form caption

---

src/OSPSuite.Core/Domain/Constants.cs
src/OSPSuite.Infrastructure.Import/Core/Mappers/DataSetToDataRepositoryMapper.cs
src/OSPSuite.Presentation/Presenters/Importer/IImportConfirmationPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImportConfirmationPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
src/OSPSuite.Presentation/Views/Importer/IImportConfirmationView.cs
src/OSPSuite.UI/Views/Importer/ImportConfirmationView.cs
tests/OSPSuite.Presentation.Tests/Importer/Services/ImporterSpecs.cs

979 default naming pattern

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Infrastructure.Import/Core/DataSourceFileParser.cs
src/OSPSuite.Infrastructure.Import/Core/DataSourceFileReaders/CsvDataSourceFile.cs
src/OSPSuite.Infrastructure.Import/Core/ErrorUnitException.cs
src/OSPSuite.Infrastructure.Import/Core/UnsupportedFileTypeException.cs
src/OSPSuite.Infrastructure.Import/Core/UnsupportedFormatException.cs
src/OSPSuite.Infrastructure.Import/Services/ICsvSeparatorSelector.cs
src/OSPSuite.Infrastructure.Import/Services/Importer.cs
src/OSPSuite.Presentation/Presenters/Importer/ICsvSeparatorSelectorPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterDataPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
src/OSPSuite.Presentation/Views/Importer/ICsvSeparatorSelectorView.cs
src/OSPSuite.UI/Services/CsvSeparatorSelector.cs
src/OSPSuite.UI/Services/DataImporter.cs
src/OSPSuite.UI/Views/Importer/CsvSeparatorSelectorView.Designer.cs
src/OSPSuite.UI/Views/Importer/CsvSeparatorSelectorView.cs
src/OSPSuite.UI/Views/Importer/CsvSeparatorSelectorView.resx
tests/OSPSuite.Presentation.Tests/Importer/Core/DataSourceFileReaders/CsvDataSourceFileSpecs.cs

How do you find the use of char '/0' as a null return? I hope this comparison is not too C++ style...

952 csv separator

---

src/OSPSuite.Infrastructure.Import/Core/DataFormat/AbstractColumnsDataFormat.cs

fixe #1009

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Core/Import/DataFormatParameter.cs
src/OSPSuite.Infrastructure.Import/Core/DataFormat/AbstractColumnsDataFormat.cs
src/OSPSuite.UI/Views/Importer/ColumnMappingView.cs

fixes #1018

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs

fixes #1054

---

src/OSPSuite.Core/Domain/Constants.cs
src/OSPSuite.UI/Services/DataImporter.cs

rename second study id

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/IColumnMappingPresenter.cs
src/OSPSuite.UI/Views/Importer/ColumnMappingView.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ColumnMappingPresenterSpecs.cs

1056 unit not updating fixed

---

src/OSPSuite.Infrastructure.Import/Core/DataSource.cs

null check

---

src/OSPSuite.UI/Views/Importer/LloqEditorView.Designer.cs
src/OSPSuite.UI/Views/Importer/MappingParameterEditorView.Designer.cs
src/OSPSuite.UI/Views/Importer/OptionsEditorView.Designer.cs
src/OSPSuite.UI/Views/Importer/UnitsEditorView.Designer.cs

1081 alignment

---

src/OSPSuite.Infrastructure.Import/Core/Mappers/DataSetToDataRepositoryMapper.cs

FindUnit instead of Unit

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Presentation/Presenters/Importer/ICsvSeparatorSelectorPresenter.cs
src/OSPSuite.Presentation/Views/Importer/ICsvSeparatorSelectorView.cs
src/OSPSuite.UI/Views/Importer/CsvSeparatorSelectorView.Designer.cs
src/OSPSuite.UI/Views/Importer/CsvSeparatorSelectorView.cs

Adding first rows to the label

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs

fixes #1078

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs

Fixes #1092 (Special icons for organs and proper order)

1092 fixing icons for organs

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ILloqEditorPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/LloqEditorPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/MappingParameterEditorPresenter.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ColumnMappingPresenterSpecs.cs

Fixes #1091 (Fix when Lloq editor is closed without changes)

do not expose numeric index but textual value instead

---

src/OSPSuite.Infrastructure.Import/Core/IUnformattedData.cs

Fixes #1102 (App crashes when sheet with headers but empty data)

Empty list check

---

src/OSPSuite.Presentation/Presenters/Importer/IImporterDataPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterDataPresenter.cs
src/OSPSuite.UI/Views/Importer/ImporterDataView.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ImporterDataPresenterSpecs.cs

fixes #1117 closing tab crash

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Infrastructure.Import/Core/PossibleUnsupportedSheetFormatException.cs
src/OSPSuite.Infrastructure.Import/Services/Importer.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs

#1108 add sheet name

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.UI/Views/Importer/ImporterDataView.Designer.cs
src/OSPSuite.UI/Views/Importer/ImporterDataView.resx

Fixes #1104 (Fix label of filters checkbox and adding tooltip)

Adding tooltip and correcting label

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
src/OSPSuite.UI/Views/Importer/ColumnMappingView.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ColumnMappingPresenterSpecs.cs

Fixes #1112 (Edit manually is always shown)

Edit manually is always shown

---

src/OSPSuite.Presentation/Presenters/Importer/ImporterDataPresenter.cs
src/OSPSuite.UI/Views/Importer/ImporterDataView.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ImporterDataPresenterSpecs.cs

fixes #1121 (closing sheets unload them also)

Adding test and logic

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Presentation/Presenters/Importer/IImporterDataPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterDataPresenter.cs
src/OSPSuite.UI/Views/Importer/ImporterDataView.cs

Fixes #1122 (Reopen all sheets)

adding reopen all sheets logic

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Infrastructure.Import/Services/Importer.cs
src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/IColumnMappingPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/IImporterDataPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterDataPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
src/OSPSuite.UI/Views/Importer/ColumnMappingView.cs

1119 configuration based on current sheet

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Core/Domain/Constants.cs
src/OSPSuite.Infrastructure.Import/Core/MetaDataCategory.cs
src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
src/OSPSuite.UI/Services/DataImporter.cs

Fixes #1095 (Plasma and Venous Blood goes to the top of the list)

1095 compartments order

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Infrastructure.Import/Core/Mappers/DataSetToDataRepositoryMapper.cs
src/OSPSuite.Infrastructure.Import/Services/Importer.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
src/OSPSuite.Presentation/Services/DataImporter.cs
tests/OSPSuite.Infrastructure.Tests/Import/DataSetToDataRepositoryMapperSpecs.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ImporterPresenterSpecs.cs

Fixes #1090 (Prompt the user before importing when different LLOQ values are present in a single data repository)

1090 check lloq is the same

---

src/OSPSuite.Presentation/Presenters/Importer/ImportConfirmationPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
src/OSPSuite.UI/Views/Importer/ImportConfirmationView.cs

fixes #991

---

src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs

Fixes #1132 (Disable preview when an error due to unordered time on the data repository)

Disable preview when an error due to unordered time on the data repository

---

src/OSPSuite.Core/Domain/Constants.cs
src/OSPSuite.Presentation/Services/DataImporter.cs

Fixes #1134 (Adding Subject Id to the list of meta data)

Add meta data

---

src/OSPSuite.Infrastructure.Import/Services/Importer.cs

fixes #1138

---

src/OSPSuite.Core/Domain/Services/ISimModelBatch.cs
src/OSPSuite.Core/Domain/Services/SimModelBatch.cs
src/OSPSuite.Core/OSPSuite.Core.csproj
src/OSPSuite.R/Domain/SimulationBatch.cs
tests/OSPSuite.Core.IntegrationTests/OSPSuite.Core.IntegrationTests.csproj
tests/OSPSuite.Core.IntegrationTests/SimModelBatchSpecs.cs
tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj
tests/OSPSuite.R.Tests/Domain/SimulationBatchSpecs.cs
tests/OSPSuite.R.Tests/OSPSuite.R.Tests.csproj
tests/OSPSuite.Starter/OSPSuite.Starter.csproj

Fixes #1113 Update to latest SimModel

Fixes #980 Expose C++ export for R

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterDataPresenter.cs

#1150 fixed

---

src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationWeightedObservedDataPresenter.cs

Fixes #1147 (Updating PI when data repository is reloaded)

Listening for the proper event

---

src/OSPSuite.Core/Domain/ModelCoreSimulationExtensions.cs
tests/OSPSuite.Core.Tests/Domain/ModelCoreSimulationExtensionsSpecs.cs

Fixes #1151 (Breaking infinite recursion when requesting PKParameters with educts and products from each other)

Keeping track of the search tree to avoid infinite recursion

---

src/OSPSuite.Infrastructure.Export/DataRepositoryExportTask.cs
tests/OSPSuite.Infrastructure.Tests/Export/DataRepositoryExportTaskSpecs.cs

#1527 fixed

---

src/OSPSuite.Infrastructure.Import/Services/IDataImporter.cs
src/OSPSuite.Presentation/Services/DataImporter.cs
tests/OSPSuite.Starter/Presenters/ImporterTestPresenter.cs

Fixes #1163 (Moving user interaction to prompt for the file path outside the service)

Moving user interaction to prompt for the file path outside the service

---

src/OSPSuite.Presentation/Presenters/Importer/ImporterDataPresenter.cs

#1168 fixed

---

src/OSPSuite.R/Services/DataImporter.cs
tests/OSPSuite.R.Tests/Services/DataImporterTaskSpecs.cs

Fixes #1176 (Using logger to show errors)

Handling errors

---

src/OSPSuite.Infrastructure.Import/Services/IDataImporter.cs
src/OSPSuite.Presentation/Services/DataImporter.cs
src/OSPSuite.R/Services/DataImporter.cs
src/OSPSuite.R/Services/DataImporterTask.cs
src/OSPSuite.R/Services/DataRepositoryTask.cs
tests/OSPSuite.R.Tests/Services/DataImporterTaskSpecs.cs
tests/OSPSuite.R.Tests/Services/DataRepositoryTaskSpecs.cs

Fixes #1174 (Configuration could be created from scratch or data and could also be saved)

1174 edit importer configuration

---

src/OSPSuite.Core/Domain/Data/QuantityValues.cs
src/OSPSuite.Core/Domain/Services/SimulationResultsCreator.cs
src/OSPSuite.R/Domain/SimulationBatch.cs
tests/OSPSuite.R.Tests/Domain/SimulationBatchSpecs.cs

Fixes #1160 (Return Jacobi matrix when runSimulation)

Adding sensitivities when the CalculateSensitivity switch is on

---

src/OSPSuite.Infrastructure.Import/Core/Mappers/DataSetToDataRepositoryMapper.cs
tests/OSPSuite.Infrastructure.Tests/Import/DataSetToDataRepositoryMapperSpecs.cs

#1187 fixed

---

src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs

Fixes #1194 (Disable confirmation view when no imported data left)

When no sheet left, disable the confirmation view

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs

Fixes #1190 (Prepare format before resetting)

Prepare format before resetting

---

src/OSPSuite.UI/Views/Importer/ColumnMappingView.cs

Fixes #1177 (Visually separating add group by)

Visually separating add group by

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.R/Services/DataImporter.cs
src/OSPSuite.R/Services/DataRepositoryTask.cs
tests/OSPSuite.R.Tests/Services/DataImporterTaskSpecs.cs
tests/OSPSuite.R.Tests/Services/DataRepositoryTaskSpecs.cs

Fixes #1191 (Adding get and create error column)

Adding get and create error column

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs

closes #1203 
As a note: I have tried writing a unit test for this, but mocking is way too complicated. Instead I am going to add an integration test in the integration test branch for exactly this scenario.

#1203 fixed

---

src/OSPSuite.R/Services/DataRepositoryTask.cs
tests/OSPSuite.R.Tests/Services/DataRepositoryTaskSpecs.cs

Fixes #1211 (Adding AddMetaData to DataRepositoryTask)

Adding AddMetaData to DataRepositoryTask

---

src/OSPSuite.UI/Views/Importer/ImporterDataView.cs

Fixes #1185 (Adding dropdown on importer tabbed view)

Adding dropdown for tab pages

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Infrastructure.Import/Core/DataSource.cs
src/OSPSuite.Infrastructure.Import/Core/EmptyDataSetsException.cs
src/OSPSuite.Infrastructure.Import/Core/IParsedDataSet.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
tests/OSPSuite.Presentation.Tests/Importer/Core/DataSourceSpecs.cs

Fixes #1193 (throw on data set with empty rows)

throw on data set with empty rows

---

src/OSPSuite.Infrastructure.Import/Core/AbstractImporterExceptions.cs
src/OSPSuite.Infrastructure.Import/Core/EmptyDataSetsException.cs
src/OSPSuite.Infrastructure.Import/Core/ErrorUnitException.cs
src/OSPSuite.Infrastructure.Import/Core/InconsistentDimensionBetweenUnitsException.cs
src/OSPSuite.Infrastructure.Import/Core/InvalidDimensionException.cs
src/OSPSuite.Infrastructure.Import/Core/MissingColumnException.cs
src/OSPSuite.Infrastructure.Import/Core/NanException.cs
src/OSPSuite.Infrastructure.Import/Core/PossibleUnsupportedSheetFormatException.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs

Fixes #1218 (Derive from abstract exception to avoid long checking when handling exception)

Refactoring exceptions

---

src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ImporterPresenterSpecs.cs

Fixes #1221 (Excluding empty mappings)

1221 exclude empty mapping

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
src/OSPSuite.UI/Views/Importer/ColumnMappingView.cs

Fixes #1222 (Moving the plus icon to the proper column on the add group by row)

Moving the plus icon to the proper column on the add group by row

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Core/Domain/Constants.cs
src/OSPSuite.Presentation/Services/DataImporter.cs
src/OSPSuite.R/Services/DataImporter.cs

Fixes #1233 (Renaming meta data and removing "Group id")

Refactoring meta data

---

src/OSPSuite.UI/Views/Importer/ImportConfirmationView.Designer.cs
src/OSPSuite.UI/Views/Importer/ImporterDataView.cs
src/OSPSuite.UI/Views/ObservedData/DataRepositoryDataView.cs

Fixes #1234 (Fixing table alignment and hiding the row indicator panel)

Visual fixes

---

src/OSPSuite.Core/Domain/Data/DataInfo.cs
tests/OSPSuite.Core.Tests/Domain/DataColumnSpecs.cs

@PavelBal  A bit disgusting but we are doing it for other stuff so ...why not :)

Fixes #1242 double lloq

---

src/OSPSuite.Infrastructure.Import/Core/Mappers/DataSetToDataRepositoryMapper.cs
tests/OSPSuite.Infrastructure.Tests/Import/DataSetToDataRepositoryMapperSpecs.cs

fixes #1241

---

src/OSPSuite.UI/Views/Importer/ColumnMappingView.cs
src/OSPSuite.UI/Views/Importer/CsvSeparatorSelectorView.cs
src/OSPSuite.UI/Views/Importer/ImporterDataView.cs
src/OSPSuite.UI/Views/Importer/LloqEditorView.cs
src/OSPSuite.UI/Views/Importer/UnitsEditorView.cs

Because of the nature of the changes I would say no unit tests are needed for this specific PR. Also ,to be honest, I am not sure where I should write a test to actually catch an exception that would go unhandled because of a missing OnEvent().

#1245 fixed

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.UI/Views/Importer/ImportConfirmationView.Designer.cs
src/OSPSuite.UI/Views/Importer/ImportConfirmationView.cs

#1258 fixed

---

src/OSPSuite.UI/Views/Importer/ColumnMappingView.cs

#1266 fixed

---

src/OSPSuite.UI/Views/Importer/MetaDataParameterEditorView.Designer.cs

Fixes #1259 (narrower modal view for edit manually on the importer)

Norrow edit manual modal

---

src/OSPSuite.UI/Views/Importer/ImporterView.Designer.cs

Fixes #1257 (wider mapping view)

mapping view is now wider

---

src/OSPSuite.Presentation/Presenters/Importer/UnitsEditorPresenter.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/UnitsEditorPresenterSpecs.cs

#1255 fixed

---

src/OSPSuite.Core/Domain/Services/ObservedDataTask.cs
src/OSPSuite.Infrastructure/OSPSuite.Infrastructure.csproj
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterReloadPresenter.cs
tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj
tests/OSPSuite.Infrastructure.Tests/OSPSuite.Infrastructure.Tests.csproj
tests/OSPSuite.Presentation.Tests/OSPSuite.Presentation.Tests.csproj
tests/OSPSuite.R.Tests/OSPSuite.R.Tests.csproj
tests/OSPSuite.UI.Tests/OSPSuite.UI.Tests.csproj

@PavelBal @georgeDaskalakis 
Going to depend expliicitely on the version 1.2.0 in core as well....just to see if we can load the damn stuff

Fixes #1283 downgrad

---

src/OSPSuite.Presentation/Presenters/Importer/UnitsEditorPresenter.cs

removing duplicate call to View.SetParams()

---

appveyor.yml
src/OSPSuite.Core/Services/IOSPSuiteLogger.cs
src/OSPSuite.Infrastructure.Import/Services/ImportLogger.cs
src/OSPSuite.Infrastructure/InfrastructureRegister.cs
src/OSPSuite.Infrastructure/OSPSuite.Infrastructure.csproj
src/OSPSuite.Infrastructure/Services/LoggingBuilderExtensions.cs
src/OSPSuite.Infrastructure/Services/OSPSuiteLogger.cs
src/OSPSuite.R/Domain/RLogger.cs
tests/OSPSuite.Infrastructure.Tests/Services/OSPSuiteLoggerSpecs.cs

1302 log file naming

---

appveyor.yml
src/OSPSuite.Infrastructure/Services/LoggingBuilderExtensions.cs

1305 log level

---

src/OSPSuite.Core/Domain/Services/ParameterIdentifications/CategorialParameterIdentificationRunInitializer.cs
src/OSPSuite.Core/Domain/Services/ParameterIdentifications/IParameterIdentificationRunInitializerFactory.cs
src/OSPSuite.Core/Domain/Services/ParameterIdentifications/JacobianMatrixCalculator.cs
src/OSPSuite.Core/Domain/Services/ParameterIdentifications/MultipleParameterIdentificationRunInitializer.cs
src/OSPSuite.Core/Domain/Services/ParameterIdentifications/ParameterIdentificationEngine.cs
src/OSPSuite.Core/Domain/Services/ParameterIdentifications/ParameterIdentificationRun.cs
src/OSPSuite.Core/Domain/Services/ParameterIdentifications/ParameterIdentificationRunInitializer.cs
src/OSPSuite.Core/Domain/Services/ParameterIdentifications/StandardParameterIdentificationRunInitializer.cs
tests/OSPSuite.Core.Tests/Domain/CategorialParameterIdentificationRunInitializerSpecs.cs
tests/OSPSuite.Core.Tests/Domain/MultipleParameterIdentificationRunInitializerSpecs.cs
tests/OSPSuite.Core.Tests/Domain/ParameterIdentificationRunSpecs.cs
tests/OSPSuite.Core.Tests/Domain/StandardParameterIdentificationRunInitializerSpecs.cs
tests/OSPSuite.Core.Tests/Services/JacobianMatrixCalculatorSpecs.cs

This should improve the starting time of a PI drastically.  a lot of stuff was done sequentially where I think it could have been done in parallel. Let's discuss to see if we want this in this version or not.
@PavelBal It would be cool if you could try this version of ospsuite.core on your super fast computer to see how the speed has improved

1301 calculation method=variation

---

src/OSPSuite.Infrastructure.Import/Core/Mappers/DataSetToDataRepositoryMapper.cs
src/OSPSuite.Infrastructure.Import/Services/Importer.cs
tests/OSPSuite.Presentation.Tests/Importer/Services/ImporterSpecs.cs

#1326 fixed

---

src/OSPSuite.Infrastructure.Import/Core/DataSource.cs
src/OSPSuite.Infrastructure.Import/Core/Mappers/DataSetToDataRepositoryMapper.cs
tests/OSPSuite.Infrastructure.Tests/Import/DataSourceSpecs.cs

Fixes #1364 (Import unit from a column" should be case insensitive)

Using FindUnit instead of HasUnit

---

src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationFeedbackPresenter.cs
src/OSPSuite.R/Services/ConcurrentSimulationRunner.cs

Fixes #1373 (Do not use acronyms)

Avoiding acronyms

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
tests/OSPSuite.Presentation.Tests/Services/DataImporterSpecs.cs

#1399 fixed

---

src/OSPSuite.Presentation/Presenters/Importer/IModalImporterPresenter.cs
src/OSPSuite.UI/Views/Importer/ModalImporterView.cs

Importer prompt before close

---

src/OSPSuite.UI/Views/Importer/ModalImporterView.cs

fixes #1430

---

src/OSPSuite.Assets/UIConstants.cs

fixes #1407

---

appveyor.yml
src/OSPSuite.Infrastructure.Import/Services/IDataImporter.cs
src/OSPSuite.Presentation/Services/DataImporter.cs
src/OSPSuite.R/Services/DataImporter.cs
src/OSPSuite.R/Services/DataImporterTask.cs
tests/OSPSuite.Presentation.Tests/Services/DataImporterSpecs.cs
tests/OSPSuite.Starter/Presenters/ImporterTestPresenter.cs
tests/OSPSuite.Starter/Tasks/ImporterConfigurationDataGenerator.cs
tests/OSPSuite.UI.Tests/Services/DataImporterSpecs.cs

initial implementation

---

src/OSPSuite.Core/Qualification/QualifcationConfiguration.cs

@Yuri05 Merging this. List of simulation names to export in the project

Fixes #1470 add list of simulation

---

OSPSuite.Core.sln
tests/OSPSuite.R.Performance/App.config
tests/OSPSuite.R.Performance/ApplicationStartup.cs
tests/OSPSuite.R.Performance/OSPSuite.R.Performance.csproj
tests/OSPSuite.R.Performance/Program.cs

Test project added
@abdelr @georgeDaskalakis @Yuri05 
Do not merge this PR. But you can use the branch 1455-performance-issue to get the code

WIP #1455 Performance issue when running in parallel

---

src/OSPSuite.Infrastructure.Import/Core/DataFormat/AbstractColumnsDataFormat.cs
src/OSPSuite.Infrastructure.Import/Core/DataFormat/DataFormatNonmem.cs
src/OSPSuite.Infrastructure.Import/Core/DataFormat/MixColumnsDataFormat.cs
src/OSPSuite.Infrastructure.Import/Core/IDataFormat.cs
src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ColumnMappingPresenterSpecs.cs

Fixes #1427 (Try to parse the unit from the column description)

try parse unit from description

---

appveyor.yml
src/OSPSuite.Presentation/Presenters/Importer/IModalImporterPresenter.cs
src/OSPSuite.Presentation/Services/DataImporter.cs

closes #1444 
@msevestre I have corrected the title of the Window, but the error in itself is not reproducible anymore. I would guess it was solved by one of the privious PR, although I am not really sure from which one.

1444 importer caption

---

appveyor.yml
src/OSPSuite.Infrastructure.Import/Services/IDataImporter.cs

1505 time dimension missing for measurement

---

src/OSPSuite.Infrastructure.Import/Core/DataSourceFile.cs
src/OSPSuite.Infrastructure.Import/Services/Importer.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterDataPresenter.cs
src/OSPSuite.Presentation/Views/Importer/IImporterDataView.cs
src/OSPSuite.UI/Views/Importer/ImporterDataView.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ImporterDataPresenterSpecs.cs

Fixes #1409 (Select the sheet on which the configuration is based on)

Select the sheet on which the configuration is based on

---

src/OSPSuite.Infrastructure.Import/Core/DataFormat/AbstractColumnsDataFormat.cs
src/OSPSuite.Infrastructure.Import/Core/IParsedDataSet.cs
tests/OSPSuite.Infrastructure.Tests/Import/DataSetToDataRepositoryMapperSpecs.cs
tests/OSPSuite.Infrastructure.Tests/Import/DataSourceSpecs.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ImporterPresenterSpecs.cs
tests/OSPSuite.Presentation.Tests/Importer/Services/ImporterSpecs.cs

Fix #1492 (Importer performs better when loading several datasets)

Importer performs better when loading several datasets

---

appveyor.yml
src/OSPSuite.Core/Domain/Constants.cs
src/OSPSuite.Infrastructure.Import/Core/DataSource.cs
src/OSPSuite.Infrastructure.Import/Core/MetaDataMappingConverter.cs
src/OSPSuite.Infrastructure.Import/Services/Importer.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ImporterPresenterSpecs.cs

1482 group by column

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ColumnMappingPresenterSpecs.cs

closes #1546 
@msevestre sorry, running the ReSharper formatter makes the review a bit harder. But at least the formating in the files is correct that way :)

1546 changing meta data malfunctions

---

src/OSPSuite.Presentation/Presenters/ObservedData/BaseDataRepositoryDataPresenter.cs
tests/OSPSuite.Presentation.Tests/Presentation/DataRepositoryDataPresenterSpecs.cs

#1578 error when right clicking on Grid Cell

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ColumnMappingPresenterSpecs.cs

1511 error unit reset fixed

---

src/OSPSuite.Core/Domain/Services/ObservedDataTask.cs
tests/OSPSuite.Core.Tests/Services/ObservedDataTaskSpecs.cs

1588 deleting empty observed data folder fixed

---

src/OSPSuite.Core/OSPSuite.Core.csproj
tests/OSPSuite.Core.IntegrationTests/OSPSuite.Core.IntegrationTests.csproj
tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj
tests/OSPSuite.Presentation.Tests/OSPSuite.Presentation.Tests.csproj
tests/OSPSuite.R.Performance/OSPSuite.R.Performance.csproj
tests/OSPSuite.R.Tests/OSPSuite.R.Tests.csproj
tests/OSPSuite.Starter/OSPSuite.Starter.csproj

Fixes #1570 Update to latest SimModel and FuncParser

---

src/OSPSuite.UI/Views/Importer/ImporterDataView.Designer.cs
src/OSPSuite.UI/Views/Importer/ImporterDataView.resx
src/OSPSuite.UI/Views/Importer/ImporterView.Designer.cs
src/OSPSuite.UI/Views/Importer/ImporterView.cs
src/OSPSuite.UI/Views/Importer/ImporterView.resx
src/OSPSuite.UI/Views/Importer/SourceFileControl.Designer.cs

1612 importer layout

---

src/OSPSuite.Core/Import/Column.cs
src/OSPSuite.Infrastructure.Import/Services/Importer.cs
tests/OSPSuite.Presentation.Tests/Importer/Services/ImporterSpecs.cs

1626 missing unit warning fixed

---

src/OSPSuite.UI/Controls/PKAnalysisPivotGridControl.cs

1639_fix_null_access_exception

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.R/Services/ContainerTask.cs
tests/OSPSuite.R.Tests/Services/ContainerTaskSpecs.cs

Fixes #1645 (GetValueByPath from ContainerTask)

GetValueByPath from ContainerTask

---

src/OSPSuite.Core/Domain/ModelCoreSimulation.cs
src/OSPSuite.Core/Domain/Services/SimulationPersistableUpdater.cs
src/OSPSuite.R/Api.cs
src/OSPSuite.R/Domain/ConcurrentRunSimulationBatch.cs
src/OSPSuite.R/Domain/Simulation.cs
src/OSPSuite.R/Services/ConcurrentSimulationRunner.cs
src/OSPSuite.R/Services/SimulationTask.cs
tests/OSPSuite.R.Tests/Domain/ConcurrentRunSimulationBatchSpecs.cs
tests/OSPSuite.R.Tests/Services/ConcurrentSimulationRunnerSpecs.cs

Cloning the simulation prevents changes to the original reference from affecting the batch once created

1691 initialize on batch create

---

src/OSPSuite.Core/Domain/DataFactory.cs
tests/OSPSuite.Core.Tests/Domain/DataFactorySpecs.cs

This should be merged first in #1633 
No tests required as all integrations test will tell us if this is a good idea or not

Fixes #1675 crash when running simulations

---

src/OSPSuite.UI/Views/Charts/CurveColorGroupingView.Designer.cs
src/OSPSuite.UI/Views/Charts/CurveColorGroupingView.cs

I made a newer branch for this fix because there were some more changes since @georgeDaskalakis branch was created.

Fixes #1635 Colour grouping button layout

---

tests/OSPSuite.Core.Tests/Services/OutputMappingMatchingTaskSpecs.cs

1728 adding tests to OutputMappingMatchingTaskSpecs

---

src/OSPSuite.Core/Domain/OutputSchema.cs
tests/OSPSuite.Core.Tests/Domain/OutputSchemaSpecs.cs
tests/OSPSuite.R.Tests/Services/ConcurrentSimulationRunnerSpecs.cs

Fixes #1737 SimulationBatch ignores sim$outputSchema$timePoints?

---

src/OSPSuite.Assets/UIConstants.cs

1741 description corrected

---

src/OSPSuite.Presentation/Presenters/SimulationOutputMappingPresenter.cs
tests/OSPSuite.Presentation.Tests/Presentation/SimulationOutputMappingPresenterSpecs.cs

1749 default scaling when changing output

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Core/Services/PredictedVsObservedChartService.cs
src/OSPSuite.Presentation/Presenters/SimulationResidualVsTimeChartPresenter.cs

1761 closing Residuals vs Time exception fixed

---

src/OSPSuite.Core/Services/PredictedVsObservedChartService.cs
tests/OSPSuite.Presentation.Tests/Presentation/PredictedVsObservedChartServiceSpecs.cs

1769 duplicate deviation lines

---

src/OSPSuite.Core/Domain/OutputMappings.cs
src/OSPSuite.Presentation/Presenters/Charts/ChartEditorPresenter.cs
src/OSPSuite.Presentation/Presenters/Charts/DataBrowserPresenter.cs

1787 adding features to simulation comparisons

---

src/OSPSuite.Presentation/Presenters/Charts/ChartEditorPresenter.cs
src/OSPSuite.Presentation/Presenters/Charts/DataBrowserPresenter.cs
src/OSPSuite.Presentation/Presenters/Charts/SimulationAnalysisChartPresenter.cs
tests/OSPSuite.Presentation.Tests/Presentation/DataBrowserPresenterSpecs.cs

1804 clearing OutputMappings in DataBrowser

---

src/OSPSuite.Core/Services/PredictedVsObservedChartService.cs
src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationPredictedVsObservedChartPresenter.cs
src/OSPSuite.Presentation/Presenters/SimulationPredictedVsObservedChartPresenter.cs
tests/OSPSuite.Presentation.Tests/Presentation/PredictedVsObservedChartServiceSpecs.cs
tests/OSPSuite.Presentation.Tests/Presentation/SimulationPredictedVsObservedChartPresenterSpecs.cs

1812 deviation lines disappear

---

src/OSPSuite.Infrastructure.Import/Core/DataFormat/AbstractColumnsDataFormat.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
tests/OSPSuite.Presentation.Tests/Services/DataImporterSpecs.cs

1822 impor observed data crash fixed

---

src/OSPSuite.Assets/UIConstants.cs

I just want to use the same strings in both Apps for context menus

Fixes #1828 create expression profiles from PKSim

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Infrastructure.Import/Core/DataSource.cs
src/OSPSuite.Infrastructure.Import/Core/Exceptions/ParseErrorDescription.cs
tests/OSPSuite.Infrastructure.Tests/Import/DataSourceSpecs.cs

1837 observed data import crashes when empty unit excel column

---

src/OSPSuite.Core/Domain/Builder/IndividualBuildingBlock.cs
src/OSPSuite.Core/Domain/Builder/OriginDataItems.cs
tests/OSPSuite.Core.Tests/Domain/IndividualBuildingBlockSpecs.cs
tests/OSPSuite.HelpersForTests/ModelHelperForSpecs.cs

Some missing UpdateProperties I discovered when implementing the CRUD stuff in MoBi

Fixes #1855 Individual Management

---

src/OSPSuite.Core/Domain/Builder/IndividualBuildingBlock.cs
src/OSPSuite.Core/Domain/Builder/OriginDataItems.cs

I needed this interface to create the ValueOriginDTO in MoBi

#1866 view and presenter for individual

---

src/OSPSuite.Infrastructure.Import/Core/DataSource.cs
tests/OSPSuite.Infrastructure.Tests/Import/DataSourceSpecs.cs

1886 importer unit for fraction not recognized

---

src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ColumnMappingPresenterSpecs.cs

2566 fixed

---

tests/OSPSuite.Core.IntegrationTests/OSPSuite.Core.IntegrationTests.csproj
tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj
tests/OSPSuite.Infrastructure.Tests/OSPSuite.Infrastructure.Tests.csproj
tests/OSPSuite.Presentation.Tests/OSPSuite.Presentation.Tests.csproj
tests/OSPSuite.R.Tests/OSPSuite.R.Tests.csproj
tests/OSPSuite.UI.Tests/OSPSuite.UI.Tests.csproj

1930 Nunit adapter updated

---

src/OSPSuite.Presentation/Presenters/Importer/IModalImporterPresenter.cs

1951 code that will surely crash

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Core/Domain/Module.cs
tests/OSPSuite.Core.Tests/Domain/ModuleSpecs.cs

Adding functionalities to  remove Start Values and to generically add IBuildingBlocks
necessary for the commands of Adding Building Blocks Start Values in MoBi
(Open-Systems-Pharmacology/MoBi#914)

Adding functionalities to  module

---

src/OSPSuite.Infrastructure.Import/Core/ColumnInfo.cs
src/OSPSuite.Infrastructure.Import/Core/DataFormat/AbstractColumnsDataFormat.cs
src/OSPSuite.Infrastructure.Import/Core/DataFormat/DataFormatHeadersWithUnits.cs
src/OSPSuite.Infrastructure.Import/Core/DataFormat/DataFormatNonmem.cs
src/OSPSuite.Infrastructure.Import/Core/DataFormat/MixColumnsDataFormat.cs
src/OSPSuite.Infrastructure.Import/Core/IDataFormat.cs
src/OSPSuite.Infrastructure.Import/Services/Importer.cs
src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterDataPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
src/OSPSuite.R/Services/DataImporterTask.cs
tests/OSPSuite.HelpersForTests/DimensionFactoryForSpecs.cs
tests/OSPSuite.Infrastructure.Tests/Import/MixColumnsDataFormatSpecs.cs
tests/OSPSuite.Presentation.Tests/Importer/Core/DataFormat/DataFormat_MetaData_CSpecs.cs
tests/OSPSuite.Presentation.Tests/Importer/Core/DataFormat/DataFormat_NonmemSpecs.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ColumnMappingPresenterSpecs.cs
tests/OSPSuite.Presentation.Tests/Importer/Services/ImporterSpecs.cs

#2019 importer parsing units made case sensitive

---

src/OSPSuite.Core/Serialization/Xml/PKMLPersistor.cs

Fixes #2069 Observed data importer configuration: formula cache

---

src/OSPSuite.Assets.Images/ApplicationIcons.cs
src/OSPSuite.Assets.Images/Icons/ModuleGreen.svg
src/OSPSuite.Assets.Images/Icons/ModuleRed.svg
src/OSPSuite.Core/Domain/Module.cs
tests/OSPSuite.Core.Tests/Domain/ModuleSpecs.cs

I don't think there are any properties of the module itself that we need to consider. ExtendedProperties don't affect the simulation and the property ReadOnly also won't affect the simulation (and I'm not really sure we are going to use it).

Fixes #2084 Module needs a version

---

.github/PULL_REQUEST_TEMPLATE.md
src/OSPSuite.Core/Domain/Mappers/IndividualParameterToParameterMapper.cs
src/OSPSuite.Core/Domain/Services/QuantityValuesUpdater.cs

Just pulling some code into a task that can be reused

Fixes #2141 Extract mapper to create parameters from individual parameters

---

src/OSPSuite.Core/Domain/ContainerExtensions.cs
src/OSPSuite.Core/Domain/EntityFormulaPath.cs
src/OSPSuite.Core/Domain/Services/FormulaTask.cs
tests/OSPSuite.Core.Tests/Domain/FormulaTaskSpecs.cs

2108 new path keywords not expanded when used in the parameter rhs

---

src/OSPSuite.UI/Views/Journal/RelatedItemsView.cs

Fixes #2148
Trying to height adjust was creating all sorts of issues .Intead, showing the grid and refreshing on bind

Fixes #2148

---

.github/PULL_REQUEST_TEMPLATE.md
src/OSPSuite.Assets.Images/ApplicationIcons.cs
src/OSPSuite.Assets.Images/Icons/PKSimModuleGreen.svg
src/OSPSuite.Assets.Images/Icons/PKSimModuleRed.svg
src/OSPSuite.Assets.Images/OSPSuite.Assets.Images.csproj
src/OSPSuite.Core/Domain/Constants.cs
src/OSPSuite.Core/Domain/Module.cs
src/OSPSuite.Presentation/Presenters/Nodes/ModuleNode.cs
tests/OSPSuite.Core.Tests/Domain/ModuleSpecs.cs

Fixes #2151 Add distinction between PK-Sim and extension modules

---

src/OSPSuite.Assets/IconNames.cs
src/OSPSuite.Core/Domain/Constants.cs
src/OSPSuite.Core/Domain/Module.cs
src/OSPSuite.Core/Serialization/Xml/ModuleXmlSerializer.cs
src/OSPSuite.Presentation/Presenters/Nodes/ModuleNode.cs
tests/OSPSuite.Core.IntegrationTests/Serializers/ModuleXmlSerializerSpecs.cs
tests/OSPSuite.Core.Tests/Domain/ModuleSpecs.cs

Fixes #2153 
Removing some of the leaks from module extended properties
https://github.com/Open-Systems-Pharmacology/docs
https://github.com/Open-Systems-Pharmacology/developer-docs

Fixes #2153 Encapsulate module extended properties within module

---

src/OSPSuite.Core/Batch/BatchOutputValues.cs
src/OSPSuite.Core/Batch/BatchSimulationExport.cs
src/OSPSuite.Core/Batch/Mappers/SimulationResultsToBatchSimulationExportMapper.cs

Fixes #2155
Add unit to output
- [x ] New feature (non-breaking change which adds functionality)
https://github.com/Open-Systems-Pharmacology/docs
https://github.com/Open-Systems-Pharmacology/developer-docs

Fixes #2155

---

src/OSPSuite.Core/Domain/Services/ModelConstructor.cs
src/OSPSuite.Core/Domain/Services/MoleculePropertiesContainerTask.cs
src/OSPSuite.Core/Domain/Services/SpatialStructureMerger.cs
tests/OSPSuite.Core.IntegrationTests/ModuleIntegrationTests.cs
tests/OSPSuite.Core.Tests/Domain/MoleculePropertiesContainerTaskSpecs.cs
tests/OSPSuite.HelpersForTests/ModelHelperForSpecs.cs
tests/OSPSuite.HelpersForTests/ModuleHelperForSpecs.cs
tests/OSPSuite.HelpersForTests/SimulationHelperForSpecs.cs

Fixes #2167
So far, the globla molecule container was only using the LAST container. I propose to merge the molecule properties container (global and local)
see https://github.com/Open-Systems-Pharmacology/MoBi/issues/1208 for bug

Fixes #2167

---

src/OSPSuite.Core/Domain/Builder/ExpressionProfileBuildingBlock.cs
src/OSPSuite.Core/Domain/Builder/IndividualParameter.cs
src/OSPSuite.Core/Domain/Builder/ObjectBaseCache.cs
src/OSPSuite.Core/Domain/Builder/PathAndValueEntity.cs
src/OSPSuite.Core/Domain/Builder/SimulationBuilder.cs
src/OSPSuite.Core/Serialization/Xml/IndividualParameterXmlSerializer.cs
src/OSPSuite.Core/Serialization/Xml/PathAndValueEntityXmlSerializer.cs

Fixes #2169 
This change is needed (or at least makes it more convenient) for grouping distributed parameters in PathAndValueEntity Building Block Presenters.
We are just promoting this property up one level in hierarchy.

Fixes #2169 Promote DistributionType from IndividualParameter to PathAndValueEntity

---

src/OSPSuite.Core/OSPSuite.Core.csproj
tests/OSPSuite.Core.IntegrationTests/OSPSuite.Core.IntegrationTests.csproj
tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj
tests/OSPSuite.R.Performance/OSPSuite.R.Performance.csproj
tests/OSPSuite.R.Tests/OSPSuite.R.Tests.csproj
tests/OSPSuite.Starter/OSPSuite.Starter.csproj

Update to consolidate all builds on 4.0.0.56

---

src/OSPSuite.Core/Domain/ObjectPathExtensions.cs
src/OSPSuite.Core/Domain/ObjectPathFactory.cs
src/OSPSuite.Core/Domain/Services/PopulationRunner.cs
src/OSPSuite.Core/Domain/Services/ScaleDivisorCalculator.cs
tests/OSPSuite.Core.IntegrationTests/PopulationDataSplitterIntegrationTests.cs
tests/OSPSuite.Core.IntegrationTests/PopulationRunnerIntegrationTests.cs
tests/OSPSuite.Core.IntegrationTests/Serializers/ObjectPathXmlSerializerSpecs.cs
tests/OSPSuite.Core.IntegrationTests/SimModelBatchSpecs.cs
tests/OSPSuite.Core.Tests/Services/ScaleDivisorCalculatorSpecs.cs
tests/OSPSuite.HelpersForTests/ConcentrationBaseModelHelperForSpecs.cs
tests/OSPSuite.HelpersForTests/ModelHelperForSpecs.cs

Fixes #2185
Code simplification to take some simple object path creation out of tasks and into an extension method
- [] Integration tests

Fixes #2185 Move simple ObjectPath creation to extension methods

---

src/OSPSuite.Presentation/Presenters/ContextMenus/ClassificationNodeContextMenu.cs

Fixes #2189
Required for 
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2840

Fixes #2189

---

src/OSPSuite.R/Services/ContainerTask.cs
tests/OSPSuite.R.Tests/Services/ContainerTaskSpecs.cs

Fixes #2211

---

src/OSPSuite.Core/Domain/ObjectPath.cs
tests/OSPSuite.Core.Tests/Domain/FormulaTaskSpecs.cs
tests/OSPSuite.Core.Tests/Domain/ObjectPathSpecs.cs

Fixes #2220 
Prevents us from making the same mistakes when appending paths together

Fixes #2220

---

src/OSPSuite.UI/Extensions/ToolTipControllerExtensions.cs

Make timeout 5 minutes. User can dismiss by moving mouse

---

src/OSPSuite.Core/Domain/Mappers/IndividualParameterToParameterMapper.cs
src/OSPSuite.Core/Extensions/PathAndValueEntityExtensions.cs
tests/OSPSuite.Core.Tests/Mappers/IndividualParameterToParameterMapperSpecs.cs

Fixes #2225 
Added some tests and a convenient extension method for checking for distributed types on ```PathAndValueEntity```

Fixes #2225 Add IsDistributed Extension method

---

src/OSPSuite.Core/Domain/Services/SpatialStructureMerger.cs

Fixes #2235 Cannot combine two modules

---

src/OSPSuite.Core/Domain/Builder/SimulationBuilder.cs
src/OSPSuite.Core/Domain/Favorites.cs
src/OSPSuite.Core/Domain/IProject.cs
src/OSPSuite.Core/Domain/Mappers/NeighborhoodCollectionToContainerMapper.cs
src/OSPSuite.Core/Domain/Module.cs
src/OSPSuite.Core/Domain/ModuleConfiguration.cs
src/OSPSuite.Core/Domain/Services/SpatialStructureMerger.cs
src/OSPSuite.Core/Serialization/Xml/ModuleConfigurationXmlSerializer.cs
src/OSPSuite.Core/Serialization/Xml/ModuleXmlSerializer.cs
src/OSPSuite.Core/Serialization/Xml/OSPSuiteXmlSerializerRepository.cs
tests/OSPSuite.Core.IntegrationTests/ModelConstructorIntegrationTests.cs
tests/OSPSuite.Core.IntegrationTests/ModuleIntegrationTests.cs
tests/OSPSuite.Core.IntegrationTests/Serializers/BuildingBlockXmlSerializerSpecs.cs
tests/OSPSuite.Core.IntegrationTests/SimulationPersistorSpecs.cs
tests/OSPSuite.Core.IntegrationTests/SpatialStructureSpecs.cs
tests/OSPSuite.Core.Tests/Domain/ModuleConfigurationSpecs.cs
tests/OSPSuite.HelpersForTests/ConstantsForSpecs.cs
tests/OSPSuite.HelpersForTests/ModuleHelperForSpecs.cs

Fixes #2240
I am introducing a `MergeBehavior` that will have to be set. I don't think it belongs in the module but more in the configuration. @rwmcintosh @PavelBal thoughts?
This is not all done yet but a good chunk is implemented. This thinking about formula does not make sense because we create NEW INSTANCES anyways. (not one formula but N formulas)

Fixes #2240

---

src/OSPSuite.Core/Domain/Module.cs
src/OSPSuite.Core/Domain/ModuleConfiguration.cs
src/OSPSuite.Core/Domain/Services/SpatialStructureMerger.cs
tests/OSPSuite.Core.IntegrationTests/ModuleIntegrationTests.cs
tests/OSPSuite.Core.Tests/Domain/ModuleConfigurationSpecs.cs
tests/OSPSuite.HelpersForTests/ModuleHelperForSpecs.cs

Fixes #2247 
Add recursion for container structure

Fixes #2247 recursive merge behavior

---

src/OSPSuite.Core/OSPSuite.Core.csproj
tests/OSPSuite.Core.IntegrationTests/OSPSuite.Core.IntegrationTests.csproj
tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj
tests/OSPSuite.Presentation.Tests/OSPSuite.Presentation.Tests.csproj
tests/OSPSuite.R.Performance/OSPSuite.R.Performance.csproj
tests/OSPSuite.R.Tests/OSPSuite.R.Tests.csproj
tests/OSPSuite.Starter/OSPSuite.Starter.csproj

Update SimModel, funcParser and CVODES

Update SimModel, funcParser and CVODES

---

src/OSPSuite.Core/Domain/Builder/NeighborhoodBuilderFactory.cs
src/OSPSuite.Core/Domain/Mappers/NeighborhoodBuilderToNeighborhoodMapper.cs
src/OSPSuite.Core/Domain/Mappers/NeighborhoodCollectionToContainerMapper.cs
src/OSPSuite.Core/Domain/ObjectPathFactory.cs
src/OSPSuite.Core/Domain/Services/ContainerMergeTask.cs
src/OSPSuite.Core/Domain/Services/SpatialStructureMerger.cs
tests/OSPSuite.Core.IntegrationTests/DataColumnToPathElementsMapperSpecs.cs
tests/OSPSuite.Core.IntegrationTests/ModuleIntegrationTests.cs
tests/OSPSuite.Core.Tests/Mappers/NeighborhoodBuilderToNeighborhoodMapperSpecs.cs
tests/OSPSuite.HelpersForTests/ModuleHelperForSpecs.cs

Fixes #2277 
merge properties and also ensure proper merge behavior for neighborhood

2277 spatial structures in extend modules tags are not extended

---

nuget_to_all.bat
rakefile.rb
src/OSPSuite.Core/Converters/v12/Converter110To120.cs
src/OSPSuite.Core/Domain/Mappers/ParameterBuilderCollectionToParameterCollectionMapper.cs
src/OSPSuite.Core/Domain/ParameterBuildMode.cs
tests/OSPSuite.Core.IntegrationTests/Serializers/MoleculeBuilderXmlSerializerSpecs.cs
tests/OSPSuite.Core.IntegrationTests/Serializers/ParameterBuilderXmlSerializerSpecs.cs
tests/OSPSuite.Core.Tests/Mappers/ParameterBuilderCollectionToParameterCollectionMapperSpecs.cs
tests/OSPSuite.HelpersForTests/ModelHelperForSpecs.cs

Fixes #2280
Removed Property build mode from database, now removed from code with project conversion

Fixes #2280 Remove parameter type "Property"

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Core/Domain/Formulas/FormulaExtensions.cs
src/OSPSuite.Presentation/DTO/ValuePointDTO.cs
src/OSPSuite.Presentation/Presenters/Parameters/EditTableParameterPresenter.cs
src/OSPSuite.Presentation/Presenters/Parameters/TableParameterPresenter.cs
src/OSPSuite.Presentation/Views/Parameters/IEditTableParameterView.cs
src/OSPSuite.Presentation/Views/Parameters/ITableParameterView.cs
src/OSPSuite.UI/Core/BaseUserControlWithValueInGrid.Designer.cs
src/OSPSuite.UI/Core/BaseUserControlWithValueInGrid.cs
src/OSPSuite.UI/Views/Parameters/EditTableParameterView.Designer.cs
src/OSPSuite.UI/Views/Parameters/EditTableParameterView.cs
src/OSPSuite.UI/Views/Parameters/TableParameterView.Designer.cs
src/OSPSuite.UI/Views/Parameters/TableParameterView.cs
tests/OSPSuite.Presentation.Tests/Presentation/EditTableParameterPresenterSpecs.cs

Fixes #2284 
We are making a more unified view for editing table formula in the apps. In short, we are going to use the PK-Sim table formula view in MoBi with the chart and easier workflow to add points

Fixes #2284

---

tests/OSPSuite.Core.IntegrationTests/BlackBoxIntegrationTests.cs
tests/OSPSuite.Core.IntegrationTests/Data/BlackBox.pkml
tests/OSPSuite.Core.IntegrationTests/OSPSuite.Core.IntegrationTests.csproj

Just added a test that verifies the behavior. The test is green so behavior is actually correct. I am keeping it because why not

Fixes #1444

---

src/OSPSuite.Core/Domain/Services/ModelConstructor.cs
src/OSPSuite.Core/Domain/Services/ModelValidator.cs
src/OSPSuite.Core/Domain/Services/QuantityValuesUpdater.cs
tests/OSPSuite.Core.IntegrationTests/ModuleIntegrationTests.cs
tests/OSPSuite.HelpersForTests/ModuleHelperForSpecs.cs

Fixes #2297
Need to replace the formula that is wrong with the constant as we add it before, BUT ONLY if the formula is not valid probably

Fixes #2297

---

src/OSPSuite.Presentation/Presenters/Parameters/TableFormulaPresenter.cs
tests/OSPSuite.Presentation.Tests/Presentation/TableFormulaPresenterSpecs.cs

Fixes #2304
Some refactoring of handling of TableFormula import

Fixes #2304 When importing a table formula, import as data repository

---

src/OSPSuite.Core/Diagram/IDiagramManager.cs
src/OSPSuite.Presentation/Diagram/BaseDiagramManager.cs

Fixes #2316 
We need to build the container structure that corresponds to container parent paths if they are set.

Fixes #2316 Add ParentPath to containers built in Diagram view

---

src/OSPSuite.Core/Domain/Exceptions.cs
src/OSPSuite.Presentation/Services/ExceptionManager.cs
tests/OSPSuite.Presentation.Tests/Presentation/ExceptionManagerSpecs.cs

Fixes #2320 Create a cancel exception and handle cancelation of commands

Fixes #2320

---

src/OSPSuite.Core/Domain/ObjectPath.cs
tests/OSPSuite.Core.Tests/Domain/ObjectPathSpecs.cs

Fixes #2308
Select a neighborhood consider parent path

#2308 Select a neighborhood consider parent path

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Core/Services/CircularReferenceChecker.cs
tests/OSPSuite.Core.Tests/Services/CircularReferenceCheckerSpecs.cs

Fixes #2325
Part 1 of a 2 part detection of circular references that will be created by formula assignment in events.

Fixes #2325 Check formula assignments in events for circular references

---

src/OSPSuite.Core/Diagram/IDiagramManager.cs
src/OSPSuite.Core/Domain/Builder/NeighborhoodBuilder.cs
src/OSPSuite.Presentation/Diagram/BaseDiagramManager.cs

Fixes #2345
Diagram needs extra options to resolve paths and nodes when the container cannot be resolved within the spatial structure.

Fixes #2345 Diagram adjustments to allow neighborhoods to ParentPath

---

src/OSPSuite.Presentation/Presenters/SensitivityAnalyses/SensitivityAnalysisResultsPresenter.cs
tests/OSPSuite.Presentation.Tests/Presentation/SensitivityAnalysisResultsPresenterSpecs.cs

Fixes #2396 Cannot start a sensitivity analysis

---

src/OSPSuite.Presentation/Presenters/ContextMenus/MultipleObservedDataFolderContextMenu.cs

Fixes #2411
Found some common code and implemented for both apps in one place

Fixes  #2411 Observed data: Multiselect folders and "Group by"

---

src/OSPSuite.UI/Views/Charts/ChartDisplayView.cs

Fixes #2432 
When zooming in on chart for time profile analysis, we get an unhandled exception.

Zoom in on chart bug

---

src/OSPSuite.UI/Views/Charts/ChartDisplayView.cs

Fixes #2436
Zooming not working ok on 3 axis

2435 zooming not working ok on 3 axis

---

src/OSPSuite.UI/Controls/InputBoxDialog.cs

Fixes #2437 
Dialog not focusing correctly when opened.

2437-add-tag-dialogue-focus-in-the-text-field

---

.github/workflows/build-and-publish.yml

Fixes  #2440 Build action: Add version to the run name
For the build action **on push**: adds the version number
Example how it will look like (taken from the tests here https://github.com/Yuri05/OSPSuite.DataBinding.DevExpress/actions):

Fixes #2440 Build action: Add version to the run name

---

src/OSPSuite.Core/Serialization/Exchange/SimulationPersistor.cs
src/OSPSuite.Core/Serialization/XElementExtensions.cs
src/OSPSuite.Core/Serialization/XElementSerializer.cs
src/OSPSuite.Core/Serialization/Xml/AbstractPersistor.cs
src/OSPSuite.Core/Serialization/Xml/DataPersistor.cs
src/OSPSuite.Core/Serialization/Xml/GroupRepositoryPersistor.cs
src/OSPSuite.Core/Serialization/Xml/PKMLPersistor.cs
src/OSPSuite.Core/Serialization/Xml/PKParameterRepositoryLoader.cs
src/OSPSuite.Core/Services/ChartTemplatePersistor.cs
tests/OSPSuite.Core.IntegrationTests/SimulationPersistorSpecs.cs
tests/OSPSuite.Starter/Presenters/ImporterTestPresenter.cs

Fixes #2449
We want to allow serialization of escaped unprintable characters and deserialization of same.

Fixes #2449 Allow more permissive Xml serialization and deserialization

---

src/OSPSuite.Assets.Images/ApplicationIcons.cs
src/OSPSuite.Assets.Images/Icons/ExportToPNG.svg
src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Core/Domain/Constants.cs
src/OSPSuite.Presentation/Presenters/Charts/ChartDisplayPresenter.cs
src/OSPSuite.Presentation/Presenters/ContextMenus/CurveChartContextMenu.cs
src/OSPSuite.Presentation/Views/Charts/IChartDisplayView.cs
src/OSPSuite.UI/Views/Charts/ChartDisplayView.cs
tests/OSPSuite.Presentation.Tests/Presentation/ChartDisplayPresenterSpecs.cs

Fixes #1801 
Include Export to PNG on the Chart

#1801 feature export chart to png

---

src/OSPSuite.Assets.Images/ApplicationIcons.cs

Fixes #1801
Fixes Icon index problem

#1801 fix icon index

---

src/OSPSuite.UI/Controls/BaseUserControl.cs

Fixes #2457
Improve draw performance

 Enable DoubleBuffering on BaseUserControl

---

src/OSPSuite.Core/Domain/Builder/SimulationBuilder.cs

Fixes #2469

---

src/OSPSuite.Core/Domain/Builder/SimulationBuilder.cs
src/OSPSuite.Core/Domain/EntitySource.cs
src/OSPSuite.Core/Domain/ModelCoreSimulationExtensions.cs
src/OSPSuite.Core/Domain/Services/EntityTracker.cs
src/OSPSuite.Core/Domain/Services/ModelConstructor.cs
src/OSPSuite.Core/Domain/Services/MoleculePropertiesContainerTask.cs
src/OSPSuite.Core/Serialization/Xml/EntitySourceXmlSerializer.cs
src/OSPSuite.Core/Services/EntitySourcePathUpdater.cs
tests/OSPSuite.Core.IntegrationTests/ModelConstructorIntegrationTests.cs
tests/OSPSuite.Core.IntegrationTests/ModuleIntegrationTests.cs
tests/OSPSuite.Core.Tests/Services/EntitySourcePathUpdaterSpecs.cs
tests/OSPSuite.Core.Tests/Services/ParameterIdentificationSimulationPathUpdaterSpecs.cs

Fixes #2471
@rwmcintosh As discussed

Fixes #2471

---

src/OSPSuite.Core/Domain/EntitySource.cs
tests/OSPSuite.Core.Tests/Domain/EntitySourcesSpecs.cs

Fixes #2473

---

src/OSPSuite.Core/Domain/Builder/SimulationBuilder.cs
src/OSPSuite.Core/Domain/EntitySource.cs
src/OSPSuite.Core/Domain/Services/EntityTracker.cs
src/OSPSuite.Core/Serialization/Xml/EntitySourceXmlSerializer.cs
tests/OSPSuite.Core.IntegrationTests/ModelConstructorIntegrationTests.cs
tests/OSPSuite.Core.IntegrationTests/ModuleIntegrationTests.cs
tests/OSPSuite.Core.Tests/Domain/EntitySourcesSpecs.cs
tests/OSPSuite.Core.Tests/Services/EntitySourcePathUpdaterSpecs.cs

Fixes #2479

---

src/OSPSuite.Core/Domain/Builder/ExpressionProfileBuildingBlock.cs
src/OSPSuite.Core/Domain/Builder/IBuilder.cs
src/OSPSuite.Core/Domain/Builder/IBuildingBlockRepository.cs
src/OSPSuite.Core/Domain/Builder/ILookupBuildingBlock.cs
src/OSPSuite.Core/Domain/Builder/InitialConditionsBuildingBlock.cs
src/OSPSuite.Core/Domain/Builder/SimulationBuilder.cs
src/OSPSuite.Core/Domain/Builder/SimulationConfiguration.cs
src/OSPSuite.Core/Domain/ModelCoreSimulation.cs
src/OSPSuite.Core/Domain/ModelCoreSimulationExtensions.cs
src/OSPSuite.Core/Domain/ModuleConfiguration.cs
src/OSPSuite.Core/Domain/Services/EntityTracker.cs
src/OSPSuite.Core/Domain/SimulationEntitySource.cs
src/OSPSuite.Core/Domain/SimulationEntitySourceReference.cs
src/OSPSuite.Core/Domain/SimulationEntitySourceReferenceFactory.cs
src/OSPSuite.Core/Serialization/Xml/SimulationEntitySourceXmlSerializer.cs
src/OSPSuite.Core/Services/EntitySourcePathUpdater.cs
src/OSPSuite.R/Domain/Simulation.cs
tests/OSPSuite.Core.IntegrationTests/ModelConstructorIntegrationTests.cs
tests/OSPSuite.Core.IntegrationTests/ModuleIntegrationTests.cs
tests/OSPSuite.Core.IntegrationTests/SimulationEntitySourceReferenceFactoryTests.cs
tests/OSPSuite.Core.Tests/Domain/EntitySourcesSpecs.cs
tests/OSPSuite.Core.Tests/Services/EntitySourcePathUpdaterSpecs.cs
tests/OSPSuite.HelpersForTests/ModelHelperForSpecs.cs
tests/OSPSuite.HelpersForTests/ModuleHelperForSpecs.cs

Fixes #2487
Move the code that was discussed from MoBi to core and add tests 

Fixes #2487

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Presentation/Presenters/SimulationOutputMappingPresenter.cs
src/OSPSuite.UI/Controls/UxGridView.cs
src/OSPSuite.UI/Views/SimulationOutputMappingView.Designer.cs
src/OSPSuite.UI/Views/SimulationOutputMappingView.cs
src/OSPSuite.UI/Views/SimulationOutputMappingView.resx
tests/OSPSuite.Presentation.Tests/Presentation/SimulationOutputMappingPresenterSpecs.cs

Fixes #2378
Allow multiple deletion on observed data

#2378 simulation observed data multi-select-for-remove-data

---

src/OSPSuite.Core/Events/ProgressDoneWithMessageEvent.cs

Fixes #2477
Add event for both Mobi and PKSim

#2477 add event

---

src/OSPSuite.Core/Domain/Services/IPopulationRunner.cs

#2506 remove warning

---

src/OSPSuite.UI/Views/HeavyWorkView.cs

Fixes #2504 
Tranpsarency was not correct when no cancel button is shown

#2504 transparency

---

tests/OSPSuite.Infrastructure.Tests/app.config

Fixes #2515 
some binding redirects needed to be added

Fixes #2515 Coverage GHA not working

---

src/OSPSuite.Presentation/Presenters/Charts/ChartDisplayPresenter.cs

Fixes #2566
Check if Chart is null

Fixes #2566 persisting chart error messages

---

src/OSPSuite.Core/Domain/Services/SimModelManager.cs

Fixes [#1970](https://github.com/Open-Systems-Pharmacology/MoBi/issues/1970)

#1970 cancel simulation

---

src/OSPSuite.Core/Qualification/QualificationConfiguration.cs

Fixes #2570
Add the ApplicationType property to QualificationConfiguration.

#2570 add application Type

---

.github/workflows/build-and-publish_v13.yml
.github/workflows/build-pr_v13.yml
.github/workflows/coverage.yml
OSPSuite.Core.sln
src/OSPSuite.Assets.Images/OSPSuite.Assets.Images.csproj
src/OSPSuite.Core/OSPSuite.Core.csproj
src/OSPSuite.Presentation/OSPSuite.Presentation.csproj
src/OSPSuite.UI/Binders/AxisBinder.cs
src/OSPSuite.UI/OSPSuite.UI.csproj
src/OSPSuite.UI/Services/DialogCreator.cs
tests/OSPSuite.Core.IntegrationTests/OSPSuite.Core.IntegrationTests.csproj
tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj
tests/OSPSuite.HelpersForTests/OSPSuite.HelpersForTests.csproj
tests/OSPSuite.Infrastructure.Tests/OSPSuite.Infrastructure.Tests.csproj
tests/OSPSuite.Presentation.Tests/OSPSuite.Presentation.Tests.csproj
tests/OSPSuite.R.Performance/OSPSuite.R.Performance.csproj
tests/OSPSuite.R.Tests/OSPSuite.R.Tests.csproj
tests/OSPSuite.Starter/OSPSuite.Starter.csproj
tests/OSPSuite.Starter/Properties/licenses.licx
tests/OSPSuite.Starter/Views/DynamicTestView.Designer.cs
tests/OSPSuite.Starter/Views/DynamicTestView.resx
tests/OSPSuite.UI.Tests/OSPSuite.UI.Tests.csproj

Fixes #2582
Update runtimes to .NET 8

update to net 8

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Infrastructure.Import/Core/Exceptions/ParseErrorDescription.cs
src/OSPSuite.Presentation/DTO/DimensionSelectionDTO.cs
src/OSPSuite.Presentation/Presenters/Importer/DimensionMappingPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterDataPresenter.cs
src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
src/OSPSuite.Presentation/Services/DataSourceToDimensionSelectionDTOMapper.cs
tests/OSPSuite.Presentation.Tests/Importer/Presenters/ImporterPresenterSpecs.cs

Fixes #2584
Adding validation fails on tabs where they are appropriate.
I put a little formatting into the text at the bottom as well.

Fixes #2584 Wrong behavior when cancelling "Dimension Select"

---

src/OSPSuite.Core/Services/ICanCopyToClipboardWithWatermark.cs
src/OSPSuite.Core/Services/ICanExportCharts.cs
src/OSPSuite.Presentation/Presenters/Charts/ChartDisplayPresenter.cs
src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationResidualHistogramPresenter.cs
src/OSPSuite.Presentation/Presenters/SensitivityAnalyses/SensitivityAnalysisPKParameterAnalysisPresenter.cs
src/OSPSuite.Presentation/Views/ParameterIdentifications/IParameterIdentificationResidualHistogramView.cs
src/OSPSuite.Presentation/Views/SensitivityAnalyses/ISensitivityAnalysisPKParameterAnalysisView.cs
src/OSPSuite.UI/Controls/UxChartControl.cs
src/OSPSuite.UI/Extensions/ChartControlExtensions.cs
src/OSPSuite.UI/Views/ParameterIdentifications/ParameterIdentificationResidualHistogramView.cs
src/OSPSuite.UI/Views/SensitivityAnalyses/SensitivityAnalysisPKParameterAnalysisView.cs
tests/OSPSuite.Presentation.Tests/Presentation/ParameterIdentificationResidualHistogramPresenterSpecs.cs
tests/OSPSuite.Presentation.Tests/Presentation/SensitivityAnalysisPKParameterAnalysisPresenterSpecs.cs

Fixes #2595 Sensitivity Analysis plot: Export to PNG not implemented
Fixes #2594 PI Histogram of Residuals plot: Export to PNG not implemented
Implementing the export for other chart types

Export to png file in SA and PI histogram

---

src/OSPSuite.Assets/Extensions/StringExtensions.cs
src/OSPSuite.CLI.Core/CLIRegister.cs
src/OSPSuite.CLI.Core/Services/CsvSeparatorSelector.cs
src/OSPSuite.CLI.Core/Services/QualificationRunner.cs
src/OSPSuite.Core/Domain/Project.cs
src/OSPSuite.Infrastructure.Export/OSPSuite.Infrastructure.Export.csproj
src/OSPSuite.Infrastructure.Import/OSPSuite.Infrastructure.Import.csproj
src/OSPSuite.Infrastructure.Serialization/Json/JsonSerializer.cs
src/OSPSuite.R/RRegister.cs
src/OSPSuite.R/Services/DataImporterTask.cs

Fixes #2623
These are core changes to support 
https://github.com/Open-Systems-Pharmacology/MoBi/issues/1958
https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/3241
The fix makes it so that Qualification Inputs that will have markdown exported are processed as soon as the project is created. This is because, in the case of MoBi qualification, the inputs only apply to the PK-Sim projects associated with the module snapshot. Those modules are recreated in PK-Sim, but the PK-Sim project and all the building blocks are not retained once the module is transferred back to MoBi.
There was also an issue where when the PKSim starter was initiated from the command line, the registration of PK-Sim services fails. That will become clear in a PK-Sim PR that's dependent on this one. To …

Fixes #2623 Export inputs as the project is created from snapshot

---

src/OSPSuite.Assets/UIConstants.cs
src/OSPSuite.Core/Domain/Services/ParameterIdentifications/ParameterIdentificationRunner.cs
src/OSPSuite.Core/Import/Column.cs
src/OSPSuite.Presentation/Services/ParameterIdentificationTask.cs
tests/OSPSuite.Presentation.Tests/Services/ParameterIdentificationTaskSpecs.cs

Fixes #2651
Parameter Identifications might be running when trying to delete them. Prevent it by showing a messasge informing which are running. 

1450 deleting a running pi should stop the pi
