Open-Systems-Pharmacology/OSPSuite.Core

- src/OSPSuite.UI/Controls/UxChartControl.cs
- src/OSPSuite.UI/Views/Charts/ChartDisplayView.Designer.cs
the barManager.SetPopupContextMenu is apparently disabling the click handler from the UxChartControl for right click.
> Fixes #97 - Cannot zoom-out after zoom-in simulated-plot

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Chart/Axis.cs
- src/OSPSuite.UI/Binders/AxisBinder.cs
- tests/OSPSuite.Core.Tests/Core/AxisSpecs.cs
- tests/OSPSuite.UI.Tests/Binders/AxisBinderSpecs.cs
- tests/OSPSuite.UI.Tests/OSPSuite.UI.Tests.csproj
That was formerly causing StackOverflowException in the event loops.
Now that we only respond to property changes once, the programs don't crash, but there was still an exception stack shown to the user because you cannot set a DevExpress Axis visual or whole range with the min > max. 
It should also not be possible to set the max to 0 for log scale. I thought about the same rule for min, but there's already an overriding behavior when you try to set min = 0 for log scale.
> Fixes #137 - Crash setting Max = 0 for log scale

- src/OSPSuite.Core/Events/FavoriteEvents.cs
- src/OSPSuite.Core/Services/FavoriteTask.cs
- tests/OSPSuite.Core.Tests/Core/FavoriteTaskSpecs.cs
Encapsulating behavior so that MoBi and PKsim and react to changes when favorites are edited in different views
> Fixes #345 Add FavoriteOrderChangedEvent to Core

- src/OSPSuite.Core/Domain/Populations/ParameterValuesCache.cs
- src/OSPSuite.Infrastructure.Import/Services/IndividualValuesCacheImporter.cs
- tests/OSPSuite.Core.Tests/Domain/IndividualValuesCacheSpecs.cs
- tests/OSPSuite.Core.Tests/Domain/ParameterValuesCacheSpecs.cs
@Yuri05 Executive decisions here. You wanted to think about it but this makes my life so much easier if I do it right.
When I import a parameter, I remove the unit it it's at the end. This is there just because we export like this.
Only issue would be for a parameter created in MoBi with a unit at the end of the name that is also added as variable in population etc.. so very very unlikely
> Remove unit from path when importing

- src/OSPSuite.UI/Controls/UxChartControl.cs
@Yuri05 This is a fix for the copy to clipboard issue
+: It works on all screen scaling 
+: It does not use that hacky code to copy stuff to clipboard
-: It is not emf so if someone needs to make the picture bigger or smaller, it might look not as good. But we have the Export options anyways so in my eyes ok
> Fixes #770 copy clipboard issue

- src/OSPSuite.Core/Domain/Data/IndividualResults.cs
- src/OSPSuite.Core/Domain/Data/SimulationResults.cs
- src/OSPSuite.R/Services/PKAnalysisTask.cs
- tests/OSPSuite.Core.IntegrationTests/Serializers/UnitXmlSerializerSpecs.cs
- tests/OSPSuite.Core.Tests/Domain/SimulationResultsSpecs.cs
- tests/OSPSuite.HelpersForTests/DimensionFactoryForSpecs.cs
- tests/OSPSuite.R.Tests/Services/PKAnalysisTaskSpecs.cs
- tests/OSPSuite.R.Tests/Services/PopulationTaskSpecs.cs
Idea: Instead of throwing an error, we make sure that we resize the Array of PK-Parameters using the max `IndividualId` in the population
so id = 0,1,2,3 => we return 4
so id = 0,1,5=> we return 6 and 2 3 4 will be fill with NaN
> 904 cannot calculate pk

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Domain/Services/ConcurrencyManager.cs
- src/OSPSuite.R/Api.cs
- src/OSPSuite.R/Domain/SimulationBatch.cs
- src/OSPSuite.R/Services/ConcurrentSimulationRunner.cs
- tests/OSPSuite.R.Tests/Services/ConcurrentSimulationRunnerSpecs.cs
Check with @msevestre why ICoreUserSettings is not available through container on Core and restore ConcurrenceManager to use this settings instead of the hardcoded 2 on MaximumNumberOfCoresToUse
> 953 enable s imulation batch with simulation concurrent runner

- src/OSPSuite.Infrastructure/Services/LoggingBuilderExtensions.cs
- tests/OSPSuite.Starter/Bootstrapping/ApplicationStartup.cs
- tests/OSPSuite.Starter/Presenters/TestPresenter.cs
- tests/OSPSuite.Starter/Views/TestView.Designer.cs
- tests/OSPSuite.Starter/Views/TestView.cs
@msevestre I have created the issue on Core since the implementation for the logger is here. I am adding the test logger to the starter. I added a button to trigger a log creation. You should notice that before clicking the button there is no log.txt file at all. Only when creating the logs, the file is created. Also, I have committed a fix. Serilog was not respecting the MinimumLogLevel. I fixed this but now we need to update PKSim and Mobi to add this change. I would think that either there is no log from the CLI (so no need for a file) or the log level was not high enough since default will filter debug and trace.
> Adding a test logger button on the starter

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Infrastructure.Import/Core/Mappers/DataSetToDataRepositoryMapper.cs
- src/OSPSuite.Presentation/Presenters/Importer/IImporterPresenter.cs
- src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
- src/OSPSuite.UI/Services/DataImporter.cs
- tests/OSPSuite.Presentation.Tests/Importer/Presenters/ImporterPresenterSpecs.cs
> Ask for file at reload #987

- src/OSPSuite.Infrastructure.Import/Core/DataFormat/MixColumnsDataFormat.cs
- tests/OSPSuite.Presentation.Tests/Importer/Services/ImporterSpecs.cs
Do not accept invalid units #982
> Do not accept invalid units #982

- src/OSPSuite.R/Services/ContainerTask.cs
- tests/OSPSuite.R.Tests/Services/ContainerTaskSpecs.cs
> Add AllStateVariableParameterPathsIn to OSPSuite.R

- src/OSPSuite.R/Services/ContainerTask.cs
- tests/OSPSuite.R.Tests/Services/ContainerTaskSpecs.cs
Sorry, I still cannot write tests (I simply don't know how it works in .NET).
This is insane, getting output values for my use case now takes 1 second as compared to 13 second through direct .net-objects access, and 34 seconds using R6 objects.
> Add methods for getting Unit and Dimension of a quantity by path

- src/OSPSuite.R/Services/DataImporterTask.cs
- tests/OSPSuite.R.Tests/Services/DataImporterTaskSpecs.cs
Fixes #1174 (Also possible to obtain the configuration, maybe edit it, and use it to load a data set)
> Could also load from an already existing configuration object

- src/OSPSuite.Presentation/Presenters/Importer/ICsvSeparatorSelectorPresenter.cs
Fixes #1181 (Truncating lines on csv to avoid enlarging the CsvSeparatorSelectrView)
> Truncating lines on csv to avoid enlarging the view

- src/OSPSuite.R/Services/DataRepositoryTask.cs
- tests/OSPSuite.R.Tests/Services/DataRepositoryTaskSpecs.cs
Fixes #1209 (When using geometric error, the dimension should not match the observation column's)
> 1209 add error column uses dimensionless on geometric error

- src/OSPSuite.R/RRegister.cs
- src/OSPSuite.R/Services/DataImporterTask.cs
Fixes #1213 (DataImporterTask should not cast to ICsvDynamicSeparatorSelector but rely on the DI mechanism)
> DataImporterTask should not cast to ICsvDynamicSeparatorSelector but rely on the DI mechanism

- src/OSPSuite.Core/Domain/Data/DataRespositoryExtensions.cs
- tests/OSPSuite.Core.Tests/Domain/DataRepositoryExtensionsSpecs.cs
Fixes #1286 (Should not crash when editing observed data with null values on extended properties)
> Null check

- src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
The issue #1293 arises because the grid does not get refreshed after the cell value gets changed. The event subscription is in line 53 in the ColumnMappingView
columnMappingGridView.CellValueChanged += (o, e) => OnEvent(_presenter.ValidateMapping);
Incorporating the refreshing of the data in the validateMapping solves the issue, but I am not sure it is optimal design - although the do get called together most of the time and refreshing the data after validation does make sense. @msevestre do you think I should create a new function in the presenter for these two calls or keep the changes the way they are now?
> #1293 fixed

- src/OSPSuite.Infrastructure.Import/Core/DataSource.cs
- src/OSPSuite.Infrastructure.Import/Core/Mappers/DataSetToDataRepositoryMapper.cs
- tests/OSPSuite.Infrastructure.Tests/Import/DataSetToDataRepositoryMapperSpecs.cs
> Skip dimension check on geometric error

- src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
- src/OSPSuite.Presentation/Presenters/Importer/IUnitsEditorPresenter.cs
- src/OSPSuite.Presentation/Presenters/Importer/UnitsEditorPresenter.cs
- src/OSPSuite.Presentation/Views/Importer/IUnitsEditorView.cs
- src/OSPSuite.UI/Views/Importer/UnitsEditorView.cs
- tests/OSPSuite.Presentation.Tests/Importer/Presenters/ColumnMappingPresenterSpecs.cs
> Setting dimension with unit

- src/OSPSuite.Presentation/Presenters/Importer/IModalImporterPresenter.cs
- src/OSPSuite.Presentation/Views/Importer/IModalImporterView.cs
- src/OSPSuite.UI/Views/Importer/ModalImporterView.cs
- tests/OSPSuite.Presentation.Tests/Importer/Presenters/ModalImporterPresenterSpecs.cs
Fixes #1460 (Do not prompt for close on import)
> Do not prompt for close on import

- src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
- tests/OSPSuite.Presentation.Tests/Importer/Presenters/ImporterPresenterSpecs.cs
Fixes #1459 (Reset mapping before loading configuration)
> Reset mapping before loading configuration

- src/OSPSuite.Presentation/Presenters/Importer/ColumnMappingPresenter.cs
- tests/OSPSuite.HelpersForTests/DomainHelperForSpecs.cs
- tests/OSPSuite.Presentation.Tests/Importer/Presenters/ColumnMappingPresenterSpecs.cs
Fixes #1499 (Do not update dimension when it already supports unit to avoid fraction/dimensionless collision)
> Do not update dimension when it already supports unit to avoid fraction/dimensionless collision

- src/OSPSuite.R/Domain/ConcurrentRunSimulationBatch.cs
- src/OSPSuite.R/Domain/SimulationBatch.cs
- src/OSPSuite.R/Services/SimulationRunner.cs
- src/OSPSuite.R/Services/SimulationTask.cs
- tests/OSPSuite.R.Tests/Services/ConcurrentSimulationRunnerSpecs.cs
@Yuri05 @msevestre @PavelBal 
When I run this test it will fail similarly often to the R code that inspired it.
The SequenceEqual test is checking that all the sequences are identical besides any from failing runs.
> a sometimes failing concurrency test

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Services/PredictedVsObservedChartService.cs
> 1759 correcting build

- src/OSPSuite.Presentation/Presenters/SimulationResidualVsTimeChartPresenter.cs
> 1807 wrong icon fixed

- src/OSPSuite.Infrastructure.Import/Core/DataSourceFileReaders/CsvDataSourceFile.cs
- tests/OSPSuite.Presentation.Tests/Services/DataImporterSpecs.cs
> 1860 unit test failing locally  fixed

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Presentation/Presenters/Commands/HistoryBrowserConfiguration.cs
- src/OSPSuite.UI/Controls/PKAnalysisPivotGridControl.cs
- src/OSPSuite.UI/Controls/UxGridView.cs
- src/OSPSuite.UI/UIConstants.cs
- src/OSPSuite.UI/Views/Commands/HistoryBrowserView.cs
- src/OSPSuite.UI/Views/Comparisons/ComparisonView.cs
- src/OSPSuite.UI/Views/ObservedData/BaseDataRepositoryDataView.cs
- src/OSPSuite.UI/Views/ParameterIdentifications/WeightedDataRepositoryDataView.cs
Moving Colors.Disabled from OSPSuite.Core.UIConstants to OSPSUite.UI.UIConstants so that we can get disabled colors from the DevExpress skin definition.
Updating uxGridView to use this value as well as the similar TextDisabled to set forecolor.
Now disabled cells in the grid look like disabled textedits. Some skins do not differentiate between disabled and enabled, but the default skin does differentiate.
> Fixes #1909 Gridview dark mode is hard to use

- src/OSPSuite.Core/Domain/Data/DataColumn.cs
- src/OSPSuite.UI/Binders/ArithmeticMeanAreaCurveBinder.cs
- src/OSPSuite.UI/Binders/ArithmeticSTDCurveBinder.cs
- src/OSPSuite.UI/Binders/CurveBinder.cs
- src/OSPSuite.UI/Binders/GeometricMeanAreaCurveBinder.cs
- src/OSPSuite.UI/Binders/GeometricStdCurveBinder.cs
- src/OSPSuite.UI/Binders/SingleValueCurveBinder.cs
We are frequently looking up the index of basegrid values so that we can use the index to get y value.
In the refresh, we can avoid searching the list over and over by using the index in the first place.
I had a project that was a bit sluggish. Profiling showed that we spent a lot of time finding the index of values in the basegrid
> Fixes #1991 curve binder refresh performance

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Domain/Builder/ExpressionTypes.cs
Formerly
- 'Metabolizing Enzyme' was just 'Enzyme'
- 'Phenotype' was 'Category'
I checked a little in PK-Sim code and there appears to be similarly named domain properties 'Category' displayed as 'Phenotype'. I don't think it's necessary to rename the domain properties for that reason.
> Fixes #2015 Small expression display caption changes

- src/OSPSuite.Core/Chart/CurveChart.cs
- src/OSPSuite.Core/Services/PredictedVsObservedChartService.cs
- src/OSPSuite.Core/Services/ResidualsVsTimeChartService.cs
- src/OSPSuite.Presentation/DTO/Charts/CurveDTO.cs
- src/OSPSuite.Presentation/Presenters/Charts/ChartDisplayPresenter.cs
- src/OSPSuite.Presentation/Presenters/Charts/SimpleChartPresenter.cs
- src/OSPSuite.Presentation/Presenters/ObservedData/DataRepositoryChartPresenter.cs
- src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationErrorHistoryFeedbackPresenter.cs
- src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationTimeProfileChartPresenter.cs
- src/OSPSuite.UI/Binders/CurveBinder.cs
- tests/OSPSuite.Core.Tests/Domain/CurveChartSpecs.cs
- tests/OSPSuite.Core.Tests/Domain/ParameterIdentificationPredictedVsObservedChartSpecs.cs
- tests/OSPSuite.Core.Tests/Services/DisplayUnitUpdaterSpecs.cs
- tests/OSPSuite.Presentation.Tests/Presentation/ChartDisplayPresenterSpecs.cs
- tests/OSPSuite.Presentation.Tests/Presentation/ChartFactorySpecs.cs
- tests/OSPSuite.Presentation.Tests/Presentation/CurveDTOSpecs.cs
- tests/OSPSuite.Presentation.Tests/Presentation/ParameterIdentificationErrorHistoryFeedbackPresenterSpecs.cs
- tests/OSPSuite.Presentation.Tests/Presentation/ParameterIdentificationTimeProfileFeedbackPresenterSpecs.cs
- tests/OSPSuite.Presentation.Tests/Presentation/PredictedVsObservedChartServiceSpecs.cs
- tests/OSPSuite.Presentation.Tests/Presentation/SimpleChartPresenterSpecs.cs
closes #2043 
note: also contains a small refactoring for the codebase to use XAxis instead of AxisBy(AxisTypes.X) since it is available and the extension of the same logic for the yAxis
> #2043 misleading axes caption fix

- src/OSPSuite.UI/Mappers/PivotGridCellsToDataTableMapper.cs
I not quite sure what this code does but the changes fixes it and I can export to excel :)
> Fixes #2096 error when exporting to excel

- src/OSPSuite.Core/Converters/v12/Converter110To120.cs
We already updated the project icons, but not the icons of the build configuration
> Fixes #2117 BuildConfiguration PSV and MSV icons not updated to the new icon name

- src/OSPSuite.Core/Domain/ObjectPath.cs
- src/OSPSuite.Core/Domain/Services/FormulaTask.cs
- tests/OSPSuite.Core.Tests/Domain/ObjectPathSpecs.cs
Fixes #2140
Adds a method to concatenate two paths. The first path is modified in place
> Fixes #2140 add functions for concatenation of 2 object paths

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Comparison/EnumerableComparer.cs
- src/OSPSuite.Core/Comparison/TableFormulaDiffBuilder.cs
- src/OSPSuite.Core/Domain/Formulas/TableFormula.cs
- src/OSPSuite.Core/Domain/Mappers/TableFormulaToDataRepositoryMapper.cs
- src/OSPSuite.Core/Domain/Services/ModelReportCreator.cs
- src/OSPSuite.Core/Serialization/SimModel/Services/TableFormulaToTableFormulaExportMapper.cs
- src/OSPSuite.Core/Serialization/Xml/FormulaXmlSerializer.cs
- tests/OSPSuite.Core.IntegrationTests/DiffBuilders/TableFormulaDiffBuilderSpecs.cs
- tests/OSPSuite.Core.IntegrationTests/Helpers/AssertForSpecs.cs
- tests/OSPSuite.Core.IntegrationTests/Serializers/DistributedTableFormulaSerializerSpecs.cs
- tests/OSPSuite.Core.Tests/Domain/TableFormulaSpecs.cs
Fixes #2161
Comparision of tables should be done by trying to find matching points by axis. Instead, two tables are equal when all points in their order are the same. So we needed to introduce  a comparison by index
> Fixes #2161:

- src/OSPSuite.Core/Domain/ObjectPath.cs
- tests/OSPSuite.Core.Tests/Domain/ObjectPathSpecs.cs
Fixes #2163 
Adding a method to ObjectPath that tests if one object path starts with another.
> Fixes #2163 Add ability to check if one ObjectPath starts with another

- src/OSPSuite.Core/Domain/Builder/MoleculeList.cs
- src/OSPSuite.Core/Domain/Builder/SimulationBuilder.cs
- src/OSPSuite.Core/Domain/Services/ObserverBuilderTask.cs
- src/OSPSuite.Core/Domain/Services/TransportCreator.cs
- tests/OSPSuite.Core.Tests/Domain/SimulationBuilderSpecs.cs
Fixes #2165 
When merging passive transports and observers, we should combine the include/exclude molecule lists
> Fixes #2165 Combining Observers and passive transports in Modules

- src/OSPSuite.Core/Domain/ObjectPath.cs
- src/OSPSuite.Core/Domain/Services/InitialConditionsCreator.cs
- tests/OSPSuite.Core.Tests/Domain/InitialConditionsCreatorSpecs.cs
Fixes #2173 
When creating initial conditions for containers whose root has an additional ```ParentPath``` property, the parent path is not prepended to the path of the initial condition.
Before:
After:
> Fixes #2173 Tumor workflow does not create molecules in any added containers

- src/OSPSuite.Core/Domain/QuantitySelection.cs
Fixes #2187 
We no longer need to force the QuantitySelection constructor to specify a type. The type is not always important for quantity selection
> Fixes #2187 Allow default QuantitySelection type of Undefined

- src/OSPSuite.Core/Domain/Services/InitialConditionsCreator.cs
- src/OSPSuite.Core/Domain/Services/ParameterValuesCreator.cs
- src/OSPSuite.Core/Domain/Services/PathAndValueCreator.cs
- tests/OSPSuite.Core.Tests/Domain/ParameterValuesCreatorSpecs.cs
Fixes #2191
See linked issue for discussion https://github.com/Open-Systems-Pharmacology/MoBi/issues/1226
In this Core PR the new code creates a list of parameter values from a given spatial structure and list of molecules. The parameter values are created for each physical container in the spatial structure and each local mode parameter in the molecule that has a constant formula
> Fixes #2191 Create parameter values for spatial structure and molecules list

- src/OSPSuite.Core/Domain/Services/ParameterValuesCreator.cs
- src/OSPSuite.Core/Extensions/ContainerModeExtensions.cs
- tests/OSPSuite.Core.Tests/Domain/ParameterValuesCreatorSpecs.cs
Fixes #2193
To make this feature implementation symmetrical with other PathAndValue extend features, we are using this core ParameterVAluesCreator to give us all the expression values for a container and selection of molecules. The expression parameters will include all the sub containers.
> Fixes #2193 Create expression profile parameters values in parameter values creator

- src/OSPSuite.UI/Extensions/ToolTipControllerExtensions.cs
Fixes #2195
The current length of time for tooltips was too short. Updated the value to be 20 seconds instead of 10. 
> Fixes #2195

- src/OSPSuite.Core/Domain/Builder/IndividualParameter.cs
- src/OSPSuite.Core/Domain/Builder/PathAndValueEntity.cs
Fixes #2199
Working on a new feature in MoBi that uses ```ParameterValue``` that are distributed. Cloning caused this property to be lost.
> Fixes #2199 Move DistributionType updates for cloning to the proper class

- src/OSPSuite.Presentation/Diagram/BaseDiagramManager.cs
Fixes #2205
I checked for similar code in V11 and added this simple thing back in.
> Fixes exception thrown when objectBase is null

- src/OSPSuite.Core/Domain/Services/ObservedDataTask.cs
- tests/OSPSuite.Core.Tests/Services/ObservedDataTaskSpecs.cs
Fixes #2001
When exporting observed data to excel, there is no LLOQ-data exported. When this export is import to PKSim or another tool, the LLOQ-information is lost. 
This fixes it by adding columns for every column containing LLOQ-data with the LLOQ-level on each row. 
> 2001 exporting observed data incl lloq

- .gitignore
- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/CoreRegister.cs
- src/OSPSuite.Core/Domain/Services/ObservedDataTask.cs
- src/OSPSuite.Core/Services/ConfirmationManager.cs
- src/OSPSuite.Core/Services/IDialogCreator.cs
- src/OSPSuite.R/MinimalImplementations/DialogCreator.cs
- src/OSPSuite.UI/Services/DialogCreator.cs
- src/OSPSuite.UI/UIConstants.cs
- tests/OSPSuite.Core.Tests/Services/ConfirmationManager.cs
- tests/OSPSuite.Core.Tests/Services/ConfirmationManagerSpecs.cs
- tests/OSPSuite.Core.Tests/Services/ObservedDataTaskSpecs.cs
Fixes #2150 
To prevent showing the same confirmationmessages over and over again, users can now suppress it when deleting observed data from a simulation until next restart.
For easily expanding this behaviour to more confirmation-messages there is confirmationMessage-type added, which has a checkbox to suppress further confirmations. This accepts a handler which executes when the checkbox is clicked and the action is confirmed. 
There is a service added, the ConfirmationManager, to hold and manage a collection of confirmations to suppress. 
Mark everything that …
> 2150 removing observed data

- src/OSPSuite.Core/Domain/Services/SpatialStructureMerger.cs
- src/OSPSuite.Presentation/UICommands/RemoveMultipleParameterIdentificationsUICommand.cs
Fixes #2234 
To support deleting more then one parameter identification from the treeview in Mobi and PKSim there is added a class 'RemoveMultipleParameterIdentifications' UICommand. 
> #2234 UICommand to Remove Multiple Parameter Identifications needed

- src/OSPSuite.Core/Domain/Services/SpatialStructureMerger.cs
- src/OSPSuite.Presentation/UICommands/RemoveMultipleParameterIdentificationsUICommand.cs
- src/OSPSuite.Presentation/UICommands/RemoveMultipleSensitivityAnalysisUICommand.cs
Fixes #2234
There is a UICommand needed to support the deletion of a multiple sensitivity-analysis at once
> Fixes #2234 multiselect context menu for sensitivity analysis

- src/OSPSuite.Core/Domain/ModelCoreSimulationExtensions.cs
Fixes #2244
The location of the applications container has changed. I think we have to look in two places now for applications
I'm unsure on the best implementation. The PR is just for discussion until then.
> Fixes #2244 PK-Analysis for multiple administration corrupted

- src/OSPSuite.Presentation/Presenters/SensitivityAnalyses/SensitivityAnalysisFeedbackPresenter.cs
Fixes #2227
The SensitivityAnalysisFeedbackView can be opened by a buttonclick in the ribbon. When the SI stops this view reverts to the starting view (inital view indicating that there is no SI running), but does not close the window. 
The fix is to hide the view on termination of the SI. 
> Fixes #2227 Sensitivity Analysis window does not close on completion

- src/OSPSuite.Core/Domain/Services/SpatialStructureMerger.cs
- src/OSPSuite.Presentation/Presenters/ContextMenus/ParameterIdentificationContextMenuItems.cs
- src/OSPSuite.Presentation/UICommands/RemoveMultipleParameterIdentificationsUICommand.cs
- src/OSPSuite.Presentation/UICommands/RunMultipleParameterIdentificationsUICommand.cs
- tests/OSPSuite.Presentation.Tests/UICommands/RunMultipleParameterIdentificationsUICommandSpecs.cs
Fixes #2234
Adds run-commands to single- and multiselect contextmenu for PI objects. 
> Fixes #2234 Adds Run-command to single and multiselect context menu for pi objects

- src/OSPSuite.Presentation/Services/DataImporter.cs
- tests/OSPSuite.UI.Tests/Services/DataImporterSpecs.cs
Fixes #2176
A calculation is made to determine if data sets are equivalent or not, one of the checks is to make sure that all the metadata is the same. In the case from the issue the metadata are different in that there is additional metadata in the new import rather than just different values. That was not taken into account
> Fixes #2176 Data importer: error when "Reload under the same settings"

- src/OSPSuite.Presentation/MenuAndBars/MenuBarCheckButton.cs
Fixes #2249
The check button was not executing commands, only actions. Now if you register a UI command, it will fire on click.
> Fixes #2249 Add UI Command execution to MenuBarCheckButton

- src/OSPSuite.UI/Controls/UxTreeView.cs
- src/OSPSuite.UI/Extensions/ToolTipControllerExtensions.cs
Fixes #2254
Added Initialize property with default value for property AutoPopDelay = 300000
> #1301 Add Initialize property to ToolTipController Extensions

- src/OSPSuite.Core/Domain/ModuleConfiguration.cs
- tests/OSPSuite.Core.IntegrationTests/ModuleIntegrationTests.cs
- tests/OSPSuite.HelpersForTests/ModuleHelperForSpecs.cs
Fixes #2258 
I think the intention of the ModuleConfiguration.MergeBehavior property is to allow the configuration to override the module default. In this case, one of the constructors was not initializing the configuration MergeBehavior to be read from the Module.DefaultMergeBehavior
> Fixes #2258 Module merge behavior "Extend" does not work

- src/OSPSuite.Core/Domain/Services/QuantityValuesUpdater.cs
- src/OSPSuite.Core/Extensions/DoubleExtensions.cs
- tests/OSPSuite.Core.IntegrationTests/ModelConstructorIntegrationTests.cs
Fixes #2261 Cannot create simulation when a module overwrites a value of a parameter with a formula
Fixes #2260
Checking that a defined start value is not NaN before using it as fixed value in a simulation parameter
> Fixes #2260 Formulas are not applied correctly

- src/OSPSuite.Core/Domain/Module.cs
- tests/OSPSuite.Core.Tests/Domain/ModuleSpecs.cs
Fixes #2271 
Added the MergeBehavior-value to take into account when calculate the version-hash
> #2271 the 'version' property of modules doesn't include the mergebehavior setting

- src/OSPSuite.Presentation/Presenters/ContextMenus/ParameterIdentificationContextMenuItems.cs
Fixes #2286
Double click is triggering first menu which is "Run", changed it to "Edit"
> #2286 double click does not open PI

- src/OSPSuite.Core/Domain/Module.cs
- src/OSPSuite.Core/Serialization/Xml/ModuleXmlSerializer.cs
- tests/OSPSuite.Core.Tests/Domain/ModuleSpecs.cs
Fixes #2302
Add serialization property IsPKSimModule so that it can set on PkSim export and used in Mobi Import and change.
> #2302 add serialization property IsPKSimModule

- src/OSPSuite.Core/Comparison/BuildingBlockDiffBuilder.cs
- src/OSPSuite.Core/Comparison/PathAndValueEntityBuildingBlockDiffBuilder.cs
- src/OSPSuite.Core/Comparison/StartValueDiffBuilder.cs
- tests/OSPSuite.Core.IntegrationTests/DiffBuilders/StartValueBuildingBlockDiffBuilderSpecs.cs
- tests/OSPSuite.Core.IntegrationTests/DiffBuilders/StartValueDiffBuilderSpecs.cs
Fixes #2310
Changing the way differences in distribution types are shown during diff building.
I'm proposing that we do not compare the values if the distribution types are different. At the level of PathAndValueEntity we cannot calculate the ultimate parameter value since we need to recreate the parameter structure to get it. We do that in other places, but during comparison, I wonder if it's necessary.
> Fixes #2310 Confusing behavior of comparison view when editing a distributed parameter in the individuals BB

- src/OSPSuite.Core/Domain/Builder/SimulationBuilder.cs
- tests/OSPSuite.Core.Tests/Domain/SimulationBuilderSpecs.cs
Fixes #2314 
Just adjusting the merge order for IC's that come from expressions vs, those that come from IC building blocks
> Fixes #2314 Initial conditions from modules are not applied

- src/OSPSuite.Core/Domain/Services/ReactionCreator.cs
- tests/OSPSuite.Core.Tests/Domain/ReactionCreatorSpecs.cs
Fixes #2318 
These root level reaction containers were always excluded from the model until this request was made to see the empty containers in the root.
> Fixes #2318 A reaction is not shown as a top-level container

- src/OSPSuite.Presentation/Mappers/DiffItemToDiffItemDTOMapper.cs
- tests/OSPSuite.Presentation.Tests/Presentation/DiffItemToDiffItemDTOMapperSpecs.cs
Fixes #2334 
Comparing individuals from different populations not showing the values as they should.
> #2334 Comparing populaitons not showing ok

- src/OSPSuite.Core/Domain/Module.cs
- tests/OSPSuite.Core.Tests/Domain/ObjectPathSpecs.cs
Fixes #2338
Cloning a module without all building blocks should make a module 'Not PKSim'.
> Fixes #2338 Clone module without some building blocks

- .gitignore
- OSPSuite.Core.v3.ncrunchsolution
- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Comparison/DiffBuilder.cs
- src/OSPSuite.Core/Comparison/StartValueDiffBuilder.cs
Fixes #2327
Adding a "Not Distributed" for comparison view when comparing a distributed vs. non distributed PathAndValueEntity
> 2327 comparison of simulation with bb when a parameter is distributed in the bb bot not in the simulation

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Domain/SensitivityAnalyses/SensitivityAnalysisRunResult.cs
- src/OSPSuite.Core/Domain/Services/SensitivityAnalyses/SensitivityAnalysisEngine.cs
- src/OSPSuite.Core/Domain/Services/SensitivityAnalyses/SensitivityAnalysisRunResultCalculator.cs
- src/OSPSuite.Presentation/Presenters/SensitivityAnalyses/SensitivityAnalysisResultsPresenter.cs
- src/OSPSuite.Presentation/Views/SensitivityAnalyses/ISensitivityAnalysisResultsView.cs
- src/OSPSuite.UI/Views/SensitivityAnalyses/SensitivityAnalysisResultsView.Designer.cs
- src/OSPSuite.UI/Views/SensitivityAnalyses/SensitivityAnalysisResultsView.cs
- tests/OSPSuite.Core.Tests/Domain/SensitivityAnalysisEngineSpecs.cs
- tests/OSPSuite.Core.Tests/Services/SensitivityAnalysisRunResultCalculatorSpecs.cs
Fixes #2351
Sensitivity analysis quietly fails if any individual run does not produce a result. The errors were not transferred to the `RunResults` so just making those available to the presenter allowed a view to show any errors.
> Fixes #2351 Simulations that error while running under sensitivity analysis do not show any error message

- src/OSPSuite.Core/Comparison/DiffBuilder.cs
- tests/OSPSuite.Core.IntegrationTests/DiffBuilders/ParameterDiffBuilderSpecs.cs
Fixes #2349 
When comparing numeric values with units, values are sometimes displayed in different units (e.g., one in dm and one in cm). This makes it difficult for users to properly interpret the differences.
Solution
Modified the CompareDoubleValues method to always use the unit of the first object for displaying both values. This ensures differences are consistently displayed in the same unit.
This change only affects the display of differences, not the underlying comparison logic or conversions.
> Modified the CompareDoubleValues method to format in consistent units

- src/OSPSuite.Core/Domain/Container.cs
- tests/OSPSuite.Core.Tests/Domain/ContainerSpecs.cs
Fixes #2353
Fix is not in the diagram code, but in the container code. We should not allow containers to have a `ParentContainer` and `ParentPath`. So, if you add a container to another container, the child container will have the `ParentPath` property cleared and the `ParentContainer` property set at the same time.
> Fixes #2353 Container not shown in diagram

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Domain/Services/SimulationConfigurationValidator.cs
- tests/OSPSuite.Core.Tests/Services/SimulationConfigurationValidatorSpecs.cs
Fixes #2358 
It's possible that two modules could define different neighborhoods that connect the same containers. This prevents the simulation from being created.
> Fixes #2358 It should not be possible to create a simulation with multiple identical neighborhoods

- src/OSPSuite.Core/Domain/Constants.cs
- src/OSPSuite.Core/Domain/Descriptors/DescriptorCriteriaExpressions.cs
- src/OSPSuite.Core/Domain/Descriptors/InChildrenCondition.cs
- src/OSPSuite.Core/Domain/Services/FormulaTask.cs
- src/OSPSuite.Core/Domain/Services/QuantityValuesUpdater.cs
- src/OSPSuite.Core/Serialization/Xml/DescriptorCriteriaXmlSerializer.cs
- tests/OSPSuite.Core.Tests/Domain/FormulaTaskSpecs.cs
- tests/OSPSuite.Core.Tests/Domain/InParentConditionSpecs.cs
Fixes #2359 
Implement In Children criteria
> Fixes #2359 

- src/OSPSuite.Core/Domain/ValidationResult.cs
- tests/OSPSuite.Core.Tests/Domain/ValidationResultSpecs.cs
Fixes #2365
Just caching the objects incorrectly during construction
> Fixes #2365 Validation of simulation fails if the same object fails

- src/OSPSuite.Core/Domain/Services/ParameterValuesCreator.cs
- tests/OSPSuite.Core.Tests/Domain/ParameterValuesCreatorSpecs.cs
Fixes #2368
The logic of setting/clearing values and formulas in ParameterValues was not correct when creating from a Parameter
> Fixes #2368 Changed simulation value not properly shown when sending simulation from PK-Sim to Mobi

- src/OSPSuite.Core/Domain/Services/ParameterValuesCreator.cs
- tests/OSPSuite.Core.Tests/Domain/ParameterValuesCreatorSpecs.cs
Fixes #2368
There was another case where updating the formula did not clear the value when ParameterValue objects are created
> Fixes #2368 also for expression

- src/OSPSuite.Core/Domain/Builder/SimulationBuilder.cs
- src/OSPSuite.Core/Domain/Builder/SimulationConfiguration.cs
- src/OSPSuite.Core/Domain/Mappers/ReactionBuilderToReactionMapper.cs
- src/OSPSuite.Core/Domain/Mappers/TransportBuilderToTransportMapper.cs
- src/OSPSuite.Core/Serialization/Xml/SimulationConfigurationXmlSerializer.cs
- tests/OSPSuite.Core.Tests/Mappers/ReactionBuilderToReactionMapperSpecs.cs
- tests/OSPSuite.Core.Tests/Mappers/TransportBuilderToTransportMapperSpecs.cs
Fixes #2372
Add a flag to `SimulationConfiguration` that overrides reaction builder and transport builder to create all process rates in a simulation
> Fixes #2372 Create all processes for a simulation

- src/OSPSuite.Assets/UIConstants.cs
Fixes #2376
There are currently separate implementations of this message in PK-Sim and MoBi. They are the same, but it makes sense only to define it once.
Also, this changes the message to add the display versions to the message where possible.
purely caption
> Fixes #2376 Consolidate invalid project version messages

- src/OSPSuite.Presentation/Presenters/AbstractExplorerPresenter.cs
- src/OSPSuite.UI/Binders/TreeNodeExplorerViewDragDropBinder.cs
- tests/OSPSuite.Starter/Presenters/ExplorerForTestPresenter.cs
Fixes #2379
In module explorer users can drag and either move, or copy building blocks between modules. The distinction needs to be recognized in CanDrag because building blocks used in a simulation can be copied, but not moved.
> Fixes #2379 Support distinct copy and move operations when dropping nodes

- src/OSPSuite.UI/Binders/TreeNodeExplorerViewDragDropBinder.cs
Fixes #2386
Copy/Move flags should be additive, not replaced
> Fixes #2386 Cannot add data to simulation?

- src/OSPSuite.Core/Comparison/ReactionBuilderDiffBuilder.cs
- src/OSPSuite.Core/Comparison/TransporterBuilderDiffBuilder.cs
- tests/OSPSuite.Core.IntegrationTests/DiffBuilders/ReactionBuilderDiffBuilderSpecs.cs
- tests/OSPSuite.Core.IntegrationTests/DiffBuilders/TransportBuilderDiffBuilderSpecs.cs
Fixes #2394 Comparison of passive transports: difference in "Create process rate" flag is not shown 
> Comparison of passive transports: difference in "Create process rate" flag is not shown #2394

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Domain/ParameterIdentifications/OptimizationRunResult.cs
- src/OSPSuite.Core/Domain/ParameterIdentifications/RunStatus.cs
- src/OSPSuite.Core/Domain/Services/ParameterIdentifications/ParameterIdentificationRun.cs
- src/OSPSuite.Core/Domain/Services/ParameterIdentifications/ParameterIdentificationRunner.cs
- src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationMatrixAnalysisPresenter.cs
- tests/OSPSuite.Core.Tests/Domain/ParameterIdentificationRunSpecs.cs
- tests/OSPSuite.Presentation.Tests/Presentation/ParameterIdentificationCorrelationMatrixPresenterSpecs.cs
- tests/OSPSuite.Presentation.Tests/Presentation/ParameterIdentificationCovarianceMatrixPresenterSpecs.cs
Fixes #2400 
During sensitivity calculations in a PI, errors are not propagated to the user. This is a special step that is not a "PI Error" so it's shown as a warning. The PI is still valid if it completed.
See #2400
> Fixes #2400 errors in pi sensitivity calculation are not obvious to the user

- src/OSPSuite.Core/Domain/Services/ParameterIdentifications/ParameterIdentificationEngine.cs
- src/OSPSuite.Core/Domain/Services/ParameterIdentifications/ParameterIdentificationRun.cs
- tests/OSPSuite.Core.Tests/Domain/ParameterIdentificationEngineSpecs.cs
- tests/OSPSuite.Core.Tests/Domain/ParameterIdentificationRunSpecs.cs
Fixes #2404
We were canceling all future runs, but not stopping the current run. The runs can take quite a lot of time.
Conversely, canceling a simulation is very fast...
> Fixes 2404 allow faster cancel from PI

- src/OSPSuite.Core/Domain/Services/ResidualCalculator.cs
- src/OSPSuite.Core/OSPSuite.Core.csproj
- tests/OSPSuite.Core.IntegrationTests/OSPSuite.Core.IntegrationTests.csproj
- tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj
- tests/OSPSuite.Core.Tests/Services/ResidualCalculatorSpecs.cs
- tests/OSPSuite.Presentation.Tests/OSPSuite.Presentation.Tests.csproj
- tests/OSPSuite.R.Performance/OSPSuite.R.Performance.csproj
- tests/OSPSuite.R.Tests/OSPSuite.R.Tests.csproj
- tests/OSPSuite.Starter/OSPSuite.Starter.csproj
Fixes #2408 
We don't want to ignore simulation outputs that are calculated as Infinity. We do want to ignore observed data that are outside the simulation time.
Using Monte Carlo
Using LM
Using NM
> Fixes #88 Invalid Parameter Identification finishes "successfully"

- src/OSPSuite.Core/Serialization/Xml/DataRepositoryXmlSerializer.cs
- tests/OSPSuite.Core.IntegrationTests/Serializers/DataRepositoryXmlSerializerSpecs.cs
Fixes #2231
Tolerating imported observed data when an extended property does not have a name. This creates a placeholder name where one is missing. See the screenshot
> Fixes #2231 Observed data: extended properties without name

- src/OSPSuite.Core/Domain/Services/PKValuesCalculator.cs
- tests/OSPSuite.Core.IntegrationTests/PKValuesCalculatorSpecs.cs
> Fixes #2453 Allow calculation of Thalf for data sets with as few as 3 data points

- src/OSPSuite.Core/Services/CircularReferenceChecker.cs
- tests/OSPSuite.Core.Tests/Services/CircularReferenceCheckerSpecs.cs
Fixes #2461
When checking circular references in event assignment do not throw exception for non-working assignments.
This kind of error (non-working assignments) are checked later and separately from circular reference checks
> Fixes #2461 Invalid paths in event assignments throws unhandled exception

- src/OSPSuite.Core/Serialization/Xml/ObjectPathXmlSerializer.cs
- tests/OSPSuite.Core.IntegrationTests/Serializers/TimePathXmlSerializerSpecs.cs
Fixes #2465
I think mapping the alias property in the serializer should be ok.
> Fixes #2465 TIME alias resetted

- src/OSPSuite.Assets/UIConstants.cs
Fixes #2475 
adding 's' on some strings
> Fixes #2475 Make default name for Reaction Building and Observer block plural

- src/OSPSuite.Core/OSPSuite.Core.csproj
Fixes #2484
This happened because the NPOI component uses `MathNet.Numerics.Signed 5.0.0`. We need to use the same assembly.
> Fixes #2484 MathNet.Numerics cannot be loaded

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Domain/ParameterIdentifications/OptimizationRunProperties.cs
- src/OSPSuite.Core/Domain/ParameterIdentifications/ParameterIdentificationRunResult.cs
- src/OSPSuite.Core/Serialization/Xml/OptimizationRunPropertiesXmlSerializer.cs
- src/OSPSuite.Core/Services/DateTimeFormatter.cs
- src/OSPSuite.Presentation/DTO/ParameterIdentifications/ParameterIdentificationRunResultDTO.cs
- src/OSPSuite.Presentation/Presenters/ParameterIdentifications/ParameterIdentificationRunPropertiesPresenter.cs
- src/OSPSuite.UI/Views/ParameterIdentifications/MultipleParameterIdentificationResultsView.cs
- tests/OSPSuite.Presentation.Tests/Presentation/ParameterIdentificationRunPropertiesPresenterSpecs.cs
Fixes #2485 
Adds the date to the summary
if it's missing
if it's present
multiple without the date
multiple with the date
> Fixes #2485 Add the completion date/time to the PI result summary

- src/OSPSuite.Core/Domain/SimulationEntitySourceReferenceFactory.cs
- tests/OSPSuite.Core.IntegrationTests/SimulationEntitySourceReferenceFactoryTests.cs
Fixes #2495
It was not working for IBb<T> but  only need the IEnumerable which is covariant
> Fixes #2495

- .github/workflows/build-pr.yml
- src/OSPSuite.Presentation/Presenters/QuantityListPresenter.cs
- src/OSPSuite.Presentation/Presenters/QuantitySelectionPresenter.cs
- src/OSPSuite.UI/Views/QuantityListView.cs
- src/OSPSuite.UI/Views/QuantitySelectionView.cs
- tests/OSPSuite.Presentation.Tests/Presentation/QuantityListPresenterSpecs.cs
- tests/OSPSuite.Presentation.Tests/Presentation/QuantitySelectionPresenterSpecs.cs
Fixes #2498
Allow the caller to hide the simulation column when selecting quantities from a single simulation
> Fixes #2498 Allow simulation column to be hidden in quantity selection

- src/OSPSuite.Presentation/Presenters/Comparisons/ComparisonPresenter.cs
- tests/OSPSuite.Presentation.Tests/Presentation/ComparisonPresenterSpecs.cs
Fixes #2500
When comparing simulations, the 'Simulation' column shows the name of only the first simulation.
> Fixes #2500 Comparison table: remove row "Simulation"

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Commands/RenameModelCommand.cs
- src/OSPSuite.R/Domain/Simulation.cs
- tests/OSPSuite.Core.Tests/Commands/RenameModelCommandSpecs.cs
- tests/OSPSuite.R.Tests/Services/SimulationRunnerIntegrationTests.cs
Fixes #2509 
when renaming a simulation results paths should not contain old name
> #2509 when renaming a simulation results paths should not contain old name

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Serialization/Exchange/SimulationPersistor.cs
- tests/OSPSuite.Core.IntegrationTests/SimulationPersistorSpecs.cs
Fixes #2525 
Serialize a simulation transfer to a string rather than a file in the file system
> Fixes #2525 Exchange of SimulationTransfer requires serialization

- src/OSPSuite.UI/Services/DiagramZoomRectangleService.cs
Fixes #2527
Discovery is that we need to use `PointToDiagram` and `DiagramToPoint` sparingly because it can trigger a recalculation of all the datapoints in the chart. 
In this example, mouseover in the gutter regions of the diagram force an all-points calculation to happen since the mouse location is not found in the XYDiagram. Luckily, there's a much faster test for this.
> Fixes #2527 Mouseover outside diagram causes all point locations to be recalculated

- src/OSPSuite.Core/Domain/Services/PKValuesCalculator.cs
- tests/OSPSuite.Core.IntegrationTests/PKValuesCalculatorSpecs.cs
Fixes #932 C_trough_tDLast not calculated properly
> Fixes #932 C_trough_tDLast not calculated properly

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Domain/Mappers/NeighborhoodCollectionToContainerMapper.cs
- src/OSPSuite.Core/Domain/Services/ModelConstructor.cs
- src/OSPSuite.Core/Domain/Services/SpatialStructureMerger.cs
- tests/OSPSuite.Core.IntegrationTests/ModuleIntegrationTests.cs
Fixes #2550
Adding warning messages when a neighborhood is not included in a simulation due to one or both neighborhoods containers not found
> Fixes #2550 Throw a warning message for non-existing neighbourhood

- src/OSPSuite.Presentation/Presenters/ContextMenus/ComparisonCommonContextMenuItems.cs
Fixes #2580
Comparison table should indicate the module when comparing building blocks. Otherwise it's confusing which is which. This cascades into a problem when exporting because the view can handle columns with the same name, but the datatable used for export to excel cannot.
module name added for module building blocks
> Fixes #2580 export of comparison results fails

- src/OSPSuite.UI/Views/Importer/ImporterDataView.cs
Fixes #2114 
Open any file and add a sheet to the import
Click again on the "source" field to select the file
A message pops up
PK-Sim®
Opening a new file will drop your currently imported data. Are you sure you want to open a new file?
Click "Yes", select a new file -> The sheet already selected for import is still shown.
NOTE: This happens when the same file is selected.
> #2114 data importer

- src/OSPSuite.Infrastructure/Services/PresenterLogger.cs
- src/OSPSuite.Infrastructure/Services/PresenterLoggerProvider.cs
Fixes #2627
During refactoring and moving of snapshot infrastructure up to core from PK-Sim, this class was copy/pasted to MoBi instead of being pulled up.
> Fixes #2627 Move PresenterLogger to core

- src/OSPSuite.Core/Domain/Builder/PathAndValueEntityBuildingBlockFromPKSim.cs
- src/OSPSuite.Core/Serialization/Xml/BuildingBlockXmlSerializer.cs
- src/OSPSuite.Core/Serialization/Xml/PKMLPersistor.cs
Fixes #2643
PR facilitates the exchange of snapshots and core building blocks between MoBi and PK-Sim
> Fixes #2643 add snapshot as property for individual and expression building blocks

- OSPSuite.Core.sln
- README.md
- src/OSPSuite.Infrastructure.Import/Core/DataSource.cs
- src/OSPSuite.Infrastructure.Import/Core/IDataSet.cs
- src/OSPSuite.Infrastructure.Import/Services/Importer.cs
- src/OSPSuite.Presentation/Presenters/Importer/ImporterPresenter.cs
- src/OSPSuite.Presentation/Services/DataSourceToDimensionSelectionDTOMapper.cs
- tests/OSPSuite.Presentation.Tests/Importer/Services/DataSourceToDimensionSelectionDTOMapperSpecs.cs
- tests/OSPSuite.Presentation.Tests/Importer/Services/ImporterSpecs.cs
Fixes #2639
We can make a special allowance for GeoStd for the dimension picker because it should always be no_dimension.
>  Wrong dimension prompt for GeoStd error when importing observed data

- src/OSPSuite.Assets/UIConstants.cs
- src/OSPSuite.Core/Domain/Services/QuantityValuesUpdater.cs
- tests/OSPSuite.Core.IntegrationTests/Services/QuantityValuesUpdaterIntegrationTests.cs
Fixes #2646
Rather than look for all individual Expression Parameters in a simulation, first check if the molecule is present and give a single warning if not.
> Performance issue with creating a simulation using Expression Profiles for proteins that are not part of the model

- src/OSPSuite.Core/Serialization/SimModel/Services/SimulationExportCreator.cs
- tests/OSPSuite.Core.Tests/OSPSuite.Core.Tests.csproj
- tests/OSPSuite.Core.Tests/Services/SimulationExportCreatorSpecs.cs
- tests/OSPSuite.HelpersForTests/OSPSuite.HelpersForTests.csproj
Fixes #2661 
Change the serialization of values exported to SimModel XML so that the strings match those exported with the .NET Framework
> Simulation runs in .NET Framework but not in .NET 8
